/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EdgeRouteImport } from './routes/edge'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesSlugRouteImport } from './routes/industries/$slug'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformSlugRouteImport } from './routes/platform/$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeRoute = EdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSlugRoute = PlatformSlugRouteImport.update({
  id: '/platform/$slug',
  path: '/platform/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/edge': typeof EdgeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/technology': typeof TechnologyRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/edge': typeof EdgeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/technology': typeof TechnologyRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/edge': typeof EdgeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/technology': typeof TechnologyRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/compliance'
    | '/connectors'
    | '/dashboard'
    | '/demo'
    | '/edge'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signin'
    | '/technology'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/platform/$slug'
    | '/solutions/$slug'
    | '/industries/'
    | '/platform/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/compliance'
    | '/connectors'
    | '/dashboard'
    | '/demo'
    | '/edge'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signin'
    | '/technology'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/platform/$slug'
    | '/solutions/$slug'
    | '/industries'
    | '/platform'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/compliance'
    | '/connectors'
    | '/dashboard'
    | '/demo'
    | '/edge'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/signin'
    | '/technology'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/platform/$slug'
    | '/solutions/$slug'
    | '/industries/'
    | '/platform/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ComplianceRoute: typeof ComplianceRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  EdgeRoute: typeof EdgeRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  SigninRoute: typeof SigninRoute
  TechnologyRoute: typeof TechnologyRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  PlatformSlugRoute: typeof PlatformSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge': {
      id: '/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof EdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$slug': {
      id: '/platform/$slug'
      path: '/platform/$slug'
      fullPath: '/platform/$slug'
      preLoaderRoute: typeof PlatformSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ComplianceRoute: ComplianceRoute,
  ConnectorsRoute: ConnectorsRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  EdgeRoute: EdgeRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  SigninRoute: SigninRoute,
  TechnologyRoute: TechnologyRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  PlatformSlugRoute: PlatformSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
