version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
    reviewers:
      - realsyncdynamics-spec
    groups:
      npm-patch:
        update-types:
          - patch
      npm-minor:
        update-types:
          - minor
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - realsyncdynamics-spec
