import { PlanKey, PlanFeatures } from './types';

export const PLAN_CONFIG: Record<PlanKey, PlanFeatures> = {
  free: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': true,
      'provenance.advanced': false,
      'c2pa.export': false,
      'team.members': false,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 25,
      monthlyRegistrations: 25,
      teamSeatsIncluded: 1,
      apiCallsMonthly: 0,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 0,
    },
  },
  bronze: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': false,
      'c2pa.export': false,
      'team.members': false,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 250,
      monthlyRegistrations: 250,
      teamSeatsIncluded: 1,
      apiCallsMonthly: 0,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 0,
    },
  },
  silver: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 2500,
      monthlyRegistrations: 2500,
      teamSeatsIncluded: 3,
      apiCallsMonthly: 10000,
      bulkJobsMonthly: 50,
      complianceExportsMonthly: 0,
    },
  },
  gold: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 25000,
      monthlyRegistrations: 25000,
      teamSeatsIncluded: 10,
      apiCallsMonthly: 100000,
      bulkJobsMonthly: 500,
      complianceExportsMonthly: 12,
    },
  },
  enterprise_public: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': true,
      'public-sector.mode': true,
    },
    limits: {
      activeAssets: null,
      monthlyRegistrations: null,
      teamSeatsIncluded: null,
      apiCallsMonthly: null,
      bulkJobsMonthly: null,
      complianceExportsMonthly: null,
    },
  },
};
