import { PlanKey, PlanFeatures } from './types';

export const PLAN_CONFIG: Record<PlanKey, PlanFeatures> = {
  free: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': true,
      'provenance.advanced': false,
      'c2pa.export': false,
      'website.scan': false,
      'website.resan': false,
      'cookie.tracking': false,
      'dsgvo.basic': false,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': false,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 25,
      monthlyRegistrations: 25,
      teamSeatsIncluded: 1,
      apiCallsMonthly: 0,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 0,
    },
  },
  bronze: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': false,
      'c2pa.export': false,
      'website.scan': false,
      'website.resan': false,
      'cookie.tracking': false,
      'dsgvo.basic': false,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': false,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 250,
      monthlyRegistrations: 250,
      teamSeatsIncluded: 1,
      apiCallsMonthly: 0,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 0,
    },
  },
  silver: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'website.scan': false,
      'website.resan': false,
      'cookie.tracking': false,
      'dsgvo.basic': false,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': false,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 2500,
      monthlyRegistrations: 2500,
      teamSeatsIncluded: 3,
      apiCallsMonthly: 10000,
      bulkJobsMonthly: 50,
      complianceExportsMonthly: 0,
    },
  },
  gold: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'website.scan': false,
      'website.resan': false,
      'cookie.tracking': false,
      'dsgvo.basic': false,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': false,
      'public-sector.mode': false,
    },
    limits: {
      activeAssets: 25000,
      monthlyRegistrations: 25000,
      teamSeatsIncluded: 10,
      apiCallsMonthly: 100000,
      bulkJobsMonthly: 500,
      complianceExportsMonthly: 12,
    },
  },
  enterprise_public: {
    features: {
      'asset.register': true,
      'asset.verify': true,
      'watermark.apply': true,
      'barcode.issue': true,
      'provenance.basic': true,
      'provenance.advanced': true,
      'c2pa.export': true,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': true,
      'public-sector.mode': true,
      'website.scan': false,
      'website.resan': false,
      'cookie.tracking': false,
      'dsgvo.basic': false,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
    },
    limits: {
      activeAssets: null,
      monthlyRegistrations: null,
      teamSeatsIncluded: null,
      apiCallsMonthly: null,
      bulkJobsMonthly: null,
      complianceExportsMonthly: null,
    },
  },
  // ── Governance OS Plans ──
  starter_governance: {
    features: {
      'website.scan': true,
      'website.resan': true,
      'cookie.tracking': true,
      'dsgvo.basic': true,
      'dsgvo.monitoring': false,
      'aiact.classification': false,
      'aiact.deeprisk': false,
      'evidence.vault': false,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': false,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': true,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
      'asset.register': false,
      'asset.verify': false,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': false,
      'provenance.advanced': false,
      'c2pa.export': false,
    },
    limits: {
      activeAssets: 1,
      monthlyRegistrations: 0,
      teamSeatsIncluded: 1,
      apiCallsMonthly: 0,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 1,
    },
    metadata: {
      productType: 'governance',
      displayName: 'Starter — Website Compliance',
      description: 'Für Einzelunternehmen, Handwerk, kleine Dienstleister',
      monthlyPrice: 39,
      yearlyPrice: null,
      target: 'Small businesses, solo entrepreneurs',
      maxAssets: 1,
    },
  },
  professional_governance: {
    features: {
      'website.scan': true,
      'website.resan': true,
      'cookie.tracking': true,
      'dsgvo.basic': true,
      'dsgvo.monitoring': true,
      'aiact.classification': true,
      'aiact.deeprisk': false,
      'evidence.vault': true,
      'policy.engine': false,
      'dpia.assessment': false,
      'vendor.screening': false,
      'automation.basic': false,
      'agents.industry': false,
      'team.members': true,
      'api.access': false,
      'bulk.jobs': false,
      'compliance.export': true,
      'org.governance': false,
      'sso.enabled': false,
      'public-sector.mode': false,
      'asset.register': false,
      'asset.verify': false,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': false,
      'provenance.advanced': false,
      'c2pa.export': false,
    },
    limits: {
      activeAssets: 10,
      monthlyRegistrations: 0,
      teamSeatsIncluded: 5,
      apiCallsMonthly: 5000,
      bulkJobsMonthly: 0,
      complianceExportsMonthly: 12,
    },
    metadata: {
      productType: 'governance',
      displayName: 'Professional — Runtime Governance',
      description: 'Für Agenturen, SaaS, KMU mit mehreren Websites',
      monthlyPrice: 149,
      yearlyPrice: null,
      target: 'Agencies, SaaS providers, SMBs',
      maxAssets: 10,
    },
  },
  governance_os: {
    features: {
      'website.scan': true,
      'website.resan': true,
      'cookie.tracking': true,
      'dsgvo.basic': true,
      'dsgvo.monitoring': true,
      'aiact.classification': true,
      'aiact.deeprisk': true,
      'evidence.vault': true,
      'policy.engine': true,
      'dpia.assessment': true,
      'vendor.screening': true,
      'automation.basic': true,
      'agents.industry': false,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': false,
      'public-sector.mode': false,
      'asset.register': false,
      'asset.verify': false,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': false,
      'provenance.advanced': false,
      'c2pa.export': false,
    },
    limits: {
      activeAssets: 50,
      monthlyRegistrations: 0,
      teamSeatsIncluded: 15,
      apiCallsMonthly: 50000,
      bulkJobsMonthly: 100,
      complianceExportsMonthly: 50,
    },
    metadata: {
      productType: 'governance',
      displayName: 'Governance OS — AI Act + DSGVO Operations',
      description: 'Dein vollständiges Governance-Betriebssystem',
      monthlyPrice: 599,
      yearlyPrice: null,
      target: 'SaaS, KI-Anbieter, regulierte Unternehmen',
      maxAssets: 50,
    },
  },
  enterprise_regulated: {
    features: {
      'website.scan': true,
      'website.resan': true,
      'cookie.tracking': true,
      'dsgvo.basic': true,
      'dsgvo.monitoring': true,
      'aiact.classification': true,
      'aiact.deeprisk': true,
      'evidence.vault': true,
      'policy.engine': true,
      'dpia.assessment': true,
      'vendor.screening': true,
      'automation.basic': true,
      'agents.industry': true,
      'team.members': true,
      'api.access': true,
      'bulk.jobs': true,
      'compliance.export': true,
      'org.governance': true,
      'sso.enabled': true,
      'public-sector.mode': true,
      'asset.register': false,
      'asset.verify': false,
      'watermark.apply': false,
      'barcode.issue': false,
      'provenance.basic': false,
      'provenance.advanced': false,
      'c2pa.export': false,
    },
    limits: {
      activeAssets: null,
      monthlyRegistrations: null,
      teamSeatsIncluded: null,
      apiCallsMonthly: null,
      bulkJobsMonthly: null,
      complianceExportsMonthly: null,
    },
    metadata: {
      productType: 'governance',
      displayName: 'Enterprise / Regulated',
      description: 'Für Health, Banking, Public Sector, kritische Prozesse',
      monthlyPrice: null,
      yearlyPrice: null,
      target: 'Healthcare, Finance, Public Sector, Enterprise',
      maxAssets: null,
    },
  },
};
