import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Check } from 'lucide-react';
import { PRICING_TIERS } from '../config/pricing';

export function RuntimeActivationSection() {
  const [url, setUrl] = useState(''); const navigate = useNavigate();
  function onSubmit(e: FormEvent) { e.preventDefault(); const trimmed = url.trim(); if (!trimmed) { navigate('/audit?source=activation'); return; } const normalized = trimmed.match(/^https?:\/\//i) ? trimmed : `https://${trimmed}`; const q = new URLSearchParams({ url: normalized, source: 'activation' }); navigate(`/audit?${q.toString()}`); }
  return <section aria-label="Start your governance journey" className="relative bg-obsidian-950 py-20 sm:py-28 px-4 sm:px-6 overflow-hidden"><div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse at 50% 30%, rgba(34,211,238,0.08) 0%, transparent 55%), radial-gradient(ellipse at 50% 80%, rgba(168,85,247,0.05) 0%, transparent 60%)' }} /><div className="relative max-w-7xl mx-auto"><div className="max-w-3xl mb-10"><div className="text-[11px] font-mono uppercase tracking-[0.18em] text-titanium-500 mb-3">05 · start</div><h2 className="text-3xl sm:text-4xl font-display font-semibold tracking-tight text-titanium-50 mb-3">Turn visibility into continuous governance.</h2><p className="text-titanium-300 text-base sm:text-lg leading-relaxed max-w-2xl">Start with a free governance scan. Then choose the runtime depth you need: continuous monitoring, AI Act governance, multi-domain operations or a dedicated enterprise environment.</p></div>
  <form onSubmit={onSubmit} className="max-w-2xl mb-12" role="search"><div className="flex flex-col sm:flex-row gap-3"><div className="flex-1 flex items-center min-h-12 bg-obsidian-900 border border-titanium-800 rounded-lg focus-within:border-cyan-400/70 focus-within:ring-2 focus-within:ring-cyan-400/10 transition-all"><span className="pl-4 font-mono text-[12px] text-titanium-500 select-none">https://</span><input type="text" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="your-company.com" autoComplete="off" spellCheck={false} className="flex-1 bg-transparent px-2 py-3 text-sm outline-none text-titanium-50 placeholder:text-titanium-600 font-mono" /></div><button type="submit" className="group inline-flex min-h-12 items-center justify-center gap-2 px-6 rounded-lg bg-cyan-400 text-obsidian-950 font-semibold text-sm tracking-tight shadow-[0_8px_28px_-12px_rgba(34,211,238,0.65)] hover:bg-cyan-300 hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300 focus-visible:ring-offset-2 focus-visible:ring-offset-obsidian-950 transition-all">Start free governance scan<ArrowRight className="h-4 w-4 group-hover:translate-x-0.5 transition-transform" /></button></div></form>
  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-px bg-titanium-900">{PRICING_TIERS.map((tier) => <article key={tier.id} className={['bg-obsidian-950 p-5 flex flex-col gap-3', tier.highlight ? 'ring-1 ring-cyan-500/40 relative' : ''].join(' ')}>{tier.highlight && <span className="absolute -top-2 right-3 px-1.5 py-0.5 bg-cyan-400 text-obsidian-950 font-mono text-[9px] uppercase tracking-wider">recommended</span>}<header><div className="font-mono text-[10px] uppercase tracking-wider text-titanium-500 mb-1">{tier.id}</div><h3 className="font-display font-semibold text-lg text-titanium-50">{tier.name}</h3></header><div><div className="font-display font-semibold text-3xl tabular-nums text-titanium-50">{tier.priceString === 'individuell' ? 'Custom' : `€ ${tier.priceString}`}</div><div className="font-mono text-[10px] text-titanium-500 mt-1">{tier.priceSuffix}</div></div><ul className="space-y-1.5 pt-3 border-t border-titanium-900/60 flex-1">{tier.bullets.slice(0, 4).map((b) => <li key={b} className="flex items-start gap-2 text-[11px] text-titanium-300"><Check className="h-3 w-3 mt-0.5 shrink-0 text-emerald-400" /><span>{b}</span></li>)}</ul><Link to={tier.cta.href} className={['group inline-flex min-h-10 items-center justify-between gap-2 px-4 py-2 rounded-md text-xs font-semibold tracking-tight transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300 focus-visible:ring-offset-2 focus-visible:ring-offset-obsidian-950', tier.highlight ? 'bg-cyan-400 text-obsidian-950 shadow-[0_6px_20px_-10px_rgba(34,211,238,0.6)] hover:bg-cyan-300 hover:-translate-y-0.5' : 'bg-obsidian-900 text-titanium-100 hover:bg-obsidian-800 hover:border-titanium-700 border border-titanium-800'].join(' ')}>{tier.cta.label}<ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" /></Link></article>)}</div><div className="mt-6 text-center font-mono text-[10px] text-titanium-500"><Link to="/pricing" className="hover:text-titanium-200 underline underline-offset-4">full plan comparison →</Link></div>
  </div></section>;
}
