import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { MouseEvent, ReactNode } from 'react';
import { Activity, ArrowRight, Menu, PlayCircle, ShieldCheck, Sparkles, X } from 'lucide-react';
import Button from './Button';
import { handleAnchorClick } from './scroll';

type HeroSectionProps = { onStart?: () => void };
type NavItem = { label: string; href: string; fallback?: string };

function Logo() {
  return <a href="#produkt" onClick={(e) => handleAnchorClick(e, '#produkt')} className="flex items-center gap-3 rounded-md text-white"><svg viewBox="0 0 32 32" className="h-8 w-8 text-cyan-400" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"><path d="M16 2v28M2 16h28M6 6l20 20M26 6L6 26" /></g><circle cx="16" cy="16" r="3" fill="currentColor" /></svg><span className="text-[17px] font-semibold tracking-tight">RealSync <span className="font-normal text-slate-300">Dynamics.AI</span></span></a>;
}

function GlassCard({ className = '', children }: { className?: string; children: ReactNode }) { return <div className={`rounded-xl border border-cyan-200/20 bg-[#061321]/85 p-4 shadow-[0_18px_55px_-20px_rgba(0,0,0,.95),0_0_35px_rgba(0,210,255,.10)] backdrop-blur-xl ${className}`}>{children}</div>; }
function Signal({ children }: { children: ReactNode }) { return <span className="inline-flex items-center gap-1.5 text-[10px] font-mono uppercase tracking-[.12em] text-cyan-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400 shadow-[0_0_10px_currentColor]" />{children}</span>; }

function Skyline() {
  return <svg viewBox="0 0 1440 330" preserveAspectRatio="none" className="absolute inset-x-0 bottom-0 z-10 h-[270px] w-full" aria-hidden="true"><defs><linearGradient id="skylineFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#10263b" stopOpacity=".05" /><stop offset="1" stopColor="#02060b" stopOpacity=".98" /></linearGradient><linearGradient id="windowGlow" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d9f8ff" stopOpacity=".9" /><stop offset="1" stopColor="#35d8ff" stopOpacity=".05" /></linearGradient></defs><rect width="1440" height="330" fill="url(#skylineFade)" /><g fill="#07131f" stroke="#4edcff" strokeOpacity=".09">{[[0,188,130,142],[110,160,90,170],[185,205,110,125],[280,145,92,185],[356,178,118,152],[462,122,76,208],[530,170,96,160],[618,104,92,226],[702,174,82,156],[770,132,112,198],[870,192,105,138],[964,145,78,185],[1030,176,120,154],[1138,128,86,202],[1212,174,108,156],[1302,146,138,184]].map(([x,y,w,h],i)=><rect key={i} x={x} y={y} width={w} height={h} />)}</g><g fill="url(#windowGlow)">{Array.from({ length: 130 }, (_, i) => <rect key={i} x={(i * 71) % 1430 + 4} y={180 + ((i * 29) % 120)} width="2.2" height="6" rx="1" />)}</g><path d="M0 270 C250 236 420 294 650 265 S1100 242 1440 276 V330 H0Z" fill="#02060b" opacity=".92" /><path d="M0 285 C270 255 450 303 690 278 S1110 258 1440 286" fill="none" stroke="#7be8ff" strokeOpacity=".10" strokeWidth="2" /></svg>;
}

export default function GovernanceHero({ onStart }: HeroSectionProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const navigate = useNavigate();
  const start = () => (onStart ? onStart() : navigate('/unified-entry/scan'));
  const navItems: NavItem[] = [{ label: 'Produkt', href: '#produkt' }, { label: 'Automatisierung', href: '#automatisierung', fallback: '#intro' }, { label: 'Evidence', href: '#evidence', fallback: '#intro' }, { label: 'AI Act', href: '#ai-act', fallback: '#intro' }, { label: 'Sicherheit', href: '#sicherheit', fallback: '#intro' }, { label: 'Preise', href: '#preise', fallback: '#intro' }];
  const handleNav = (event: MouseEvent<HTMLAnchorElement>, href: string, fallback = '#intro') => document.querySelector(href) ? handleAnchorClick(event, href) : handleAnchorClick(event, fallback);

  return <section id="produkt" className="relative isolate min-h-[100svh] overflow-hidden bg-[#02060b] text-white">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_30%,rgba(30,188,255,.20),transparent_31%),radial-gradient(circle_at_82%_76%,rgba(255,183,78,.14),transparent_24%),linear-gradient(180deg,#02060b_0%,#061523_54%,#02060b_100%)]" />
    <div className="absolute right-[-8%] top-[8%] h-[620px] w-[620px] rounded-full bg-cyan-400/10 blur-[130px]" /><div className="absolute right-[10%] top-[13%] h-24 w-24 rounded-full bg-white/90 blur-[7px] shadow-[0_0_100px_42px_rgba(255,193,113,.28)]" /><div className="absolute inset-x-0 bottom-0 z-20 h-72 bg-gradient-to-t from-[#02060b] via-[#02060b]/55 to-transparent" />

    <header className="relative z-[60] mx-auto flex max-w-[1400px] items-center justify-between px-5 py-6 lg:px-10"><Logo /><nav className="hidden items-center gap-9 text-sm text-slate-200 lg:flex" aria-label="Hauptnavigation">{navItems.map((item) => <a key={item.label} href={item.href} onClick={(e) => handleNav(e, item.href, item.fallback)} className="transition hover:text-white">{item.label}</a>)}</nav><div className="hidden items-center gap-4 lg:flex"><a href="/welcome" className="px-3 py-2 text-sm text-slate-300 hover:text-white">Login</a><Button onClick={start} variant="primary" size="md">Kostenlos starten <ArrowRight className="h-4 w-4" /></Button></div><button type="button" aria-label={menuOpen ? 'Menü schließen' : 'Menü öffnen'} aria-expanded={menuOpen} onClick={() => setMenuOpen((v) => !v)} className="rounded-lg border border-white/15 p-2 lg:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></header>
    {menuOpen && <div className="relative z-[70] mx-5 rounded-xl border border-white/10 bg-[#061321]/95 p-4 backdrop-blur-xl lg:hidden"><nav className="flex flex-col gap-1">{navItems.map((item) => <a key={item.label} href={item.href} onClick={(e) => { handleNav(e, item.href, item.fallback); setMenuOpen(false); }} className="rounded-lg px-3 py-2.5 text-sm text-slate-200 hover:bg-white/5">{item.label}</a>)}<a href="/welcome" className="rounded-lg px-3 py-2.5 text-sm text-slate-200">Login</a><Button onClick={() => { setMenuOpen(false); start(); }} variant="primary" size="md" className="mt-2 w-full justify-center">Kostenlos starten <ArrowRight className="h-4 w-4" /></Button></nav></div>}

    <div className="relative z-30 mx-auto grid max-w-[1400px] grid-cols-1 items-center px-5 pb-28 pt-4 lg:grid-cols-[47%_53%] lg:px-10 lg:pt-0">
      <div className="relative z-40 max-w-[680px] pt-5 lg:pt-12"><a href="#intro" onClick={(e) => handleAnchorClick(e, '#intro')} className="mb-7 inline-flex items-center gap-2 rounded-full border border-cyan-300/40 bg-cyan-300/10 px-4 py-2 font-mono text-xs font-semibold uppercase tracking-[.12em] text-cyan-100 shadow-[0_0_30px_rgba(34,211,238,.12)]"><span className="rounded-full bg-cyan-300 px-2 py-0.5 text-[9px] font-bold text-[#03202a]">NEU</span> CLAUDE CODE OPTIMIZER <ArrowRight className="h-3.5 w-3.5" /></a><h1 className="text-balance text-[58px] font-black leading-[.88] tracking-[-.055em] sm:text-[72px] lg:text-[82px] xl:text-[94px]" style={{ textShadow: '0 2px 0 #c9dceb,0 4px 0 #7895ad,0 7px 0 #304c66,0 13px 28px rgba(0,0,0,.85),0 0 44px rgba(100,220,255,.25)' }}><span className="block bg-gradient-to-b from-white via-[#dff2ff] to-[#7897b2] bg-clip-text text-transparent">AI Governance</span><span className="block bg-gradient-to-b from-white via-[#d6ecff] to-[#6f8da9] bg-clip-text text-transparent">Runtime</span></h1><p className="mt-7 max-w-[620px] text-xl leading-8 text-slate-100 sm:text-2xl">Das KI-Betriebssystem für <span className="font-semibold text-cyan-300">DSGVO, EU AI Act &amp; Code-Compliance.</span></p><p className="mt-5 max-w-[620px] text-base leading-7 text-slate-300 sm:text-lg">Kontinuierliche Governance, Monitoring und beweisfähige Evidence für KI-Systeme, Daten und Code – in einer operativen Control Plane.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={start} variant="primary" size="lg">Kostenlos starten <ArrowRight className="h-5 w-5" /></Button><a href="#intro" onClick={(e) => handleAnchorClick(e, '#intro')} className="inline-flex h-12 items-center gap-2 rounded-xl border border-white/20 bg-white/[.045] px-5 text-sm font-medium text-white backdrop-blur-md transition hover:bg-white/10"><PlayCircle className="h-4 w-4" />Plattform ansehen</a></div><div className="mt-6 flex flex-wrap gap-2">{['GDPR','Risk Score','Claude Code Audit','EU AI Act'].map((item) => <span key={item} className="rounded-full border border-cyan-300/35 bg-[#061321]/75 px-4 py-2 text-xs font-medium text-cyan-200">{item}</span>)}</div></div>

      <div className="relative min-h-[650px] lg:min-h-[720px]" aria-label="Europa Satellitenansicht und Governance telemetry"><div className="absolute -right-[17%] top-[-3%] h-[700px] w-[900px] max-w-none"><div className="absolute inset-[8%] rounded-full bg-cyan-300/10 blur-3xl" /><img src="/europe-globe.webp" alt="Europa bei Nacht aus Satellitenperspektive" className="absolute inset-0 h-full w-full object-contain drop-shadow-[0_0_95px_rgba(59,208,255,.35)]" /><div className="absolute right-[14%] top-[13%] h-20 w-20 rounded-full bg-white/85 blur-[7px] shadow-[0_0_90px_32px_rgba(255,193,113,.28)]" /></div>
        <GlassCard className="absolute left-[2%] top-[8%] z-30 w-44"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-8 w-8 text-cyan-300" /><div><div className="text-sm font-semibold">DSGVO</div><div className="text-xs text-slate-300">Compliant</div></div></div></GlassCard>
        <GlassCard className="absolute right-[3%] top-[22%] z-30 w-40"><Signal>Risk Score</Signal><div className="mt-1 text-4xl font-light">87<span className="text-lg text-slate-400">/100</span></div><div className="mt-2 h-1 rounded-full bg-slate-700"><div className="h-full w-[87%] rounded-full bg-cyan-400 shadow-[0_0_12px_#22d3ee]" /></div></GlassCard>
        <GlassCard className="absolute left-[22%] top-[49%] z-30 w-44"><Signal>Evidence</Signal><div className="mt-1 text-3xl font-semibold">1,248</div><div className="text-xs text-slate-400">Nachweise</div></GlassCard>
        <GlassCard className="absolute right-[19%] top-[43%] z-30 w-64"><Signal>Claude Code Audit</Signal><div className="mt-2 flex items-baseline gap-2"><span className="text-4xl font-light">94.2%</span><span className="text-xs text-slate-300">Code-Ready</span></div><p className="mt-2 text-xs leading-5 text-slate-300">Analysierte Codezeilen: 2.1 Mio<br />Sicherheitslücken behoben: 11,350</p></GlassCard>
        <GlassCard className="absolute left-[45%] top-[70%] z-30 w-44"><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-cyan-300" /><div><div className="text-sm font-medium">MONITORING</div><div className="text-xs text-slate-300">Live <span className="text-emerald-400">●</span></div></div></div></GlassCard>
        <GlassCard className="absolute right-[3%] top-[68%] z-30 w-44"><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-cyan-300" /><div className="text-sm font-semibold">EU AI ACT<br />READY</div></div></GlassCard>
      </div>
    </div>
    <Skyline />
    <div className="absolute bottom-5 left-1/2 z-30 hidden -translate-x-1/2 text-center sm:block"><div className="mb-2 text-[10px] font-medium uppercase tracking-[.2em] text-slate-400">EUROPEAN AI GOVERNANCE</div><div className="flex items-center gap-8 whitespace-nowrap text-xs font-semibold text-slate-300/80"><span>GDPR</span><span>EU AI ACT</span><span>CODE SECURITY</span><span>EVIDENCE</span><span>CONTINUOUS MONITORING</span></div></div>
  </section>;
}
