// Supabase Database Types — autogenerated via supabase gen types
// Für Phase 1: simplified. Phase 2: vollständig generiert.

export interface Database {
  public: {
    Tables: {
      evidence_snapshots: {
        Row: {
          id: string;
          tenant_id: string;
          subject_ref: string;
          label: string | null;
          version: number;
          content_sha256: string;
          prev_hash: string | null;
          event_hash: string;
          signature: string | null;
          retention_class: string;
          retained_until: string | null;
          created_by: string | null;
          created_at: string;
          // Exakt in den event_hash eingegangener Zeitstempel. NULL bei
          // Snapshots von vor Einführung der Spalte — die sind nur
          // strukturell prüfbar, gelten aber nicht als manipuliert.
          event_timestamp: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          subject_ref: string;
          label?: string | null;
          version: number;
          content_sha256: string;
          prev_hash?: string | null;
          event_hash: string;
          signature?: string | null;
          retention_class?: string;
          retained_until?: string | null;
          created_by?: string | null;
          created_at?: string;
          event_timestamp?: string | null;
        };
        // Append-only: die Tabelle hat einen Immutability-Trigger. Der leere
        // Update-Typ macht schon im Compiler klar, dass es nichts zu ändern gibt.
        Update: Record<string, never>;
        Relationships: [];
      };
      tenants: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          name?: string;
        };
        Relationships: [];
      };
      mcp_api_keys: {
        Row: {
          id: string;
          tenant_id: string;
          key_prefix: string;
          key_hash: string;
          name: string | null;
          scopes: string[];
          created_by: string | null;
          created_at: string;
          expires_at: string | null;
          last_used_at: string | null;
          last_used_ip: string | null;
          active: boolean;
          rotated_from: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key_prefix: string;
          key_hash: string;
          name?: string | null;
          scopes?: string[];
          created_by?: string | null;
          created_at?: string;
          expires_at?: string | null;
          active?: boolean;
          rotated_from?: string | null;
        };
        Update: {
          name?: string | null;
          scopes?: string[];
          expires_at?: string | null;
          active?: boolean;
        };
        Relationships: [];
      };
      mcp_key_usage: {
        Row: {
          id: string;
          key_id: string;
          action: string;
          status: number;
          ip_address: string | null;
          user_agent: string | null;
          timestamp: string;
          latency_ms: number | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          key_id: string;
          action: string;
          status: number;
          ip_address?: string | null;
          user_agent?: string | null;
          timestamp?: string;
          latency_ms?: number | null;
          error_message?: string | null;
        };
        // Append-only: die Tabelle hat einen Immutability-Trigger. Der leere
        // Update-Typ macht schon im Compiler klar, dass es nichts zu ändern gibt.
        Update: Record<string, never>;
        Relationships: [];
      };
    };
    Views: {};
    Functions: {
      evidence_vault_timeline: {
        Args: {
          p_tenant_id: string;
          p_limit?: number;
        };
        Returns: Array<{
          id: string;
          subject_ref: string;
          label: string | null;
          version: number;
          content_sha256: string;
          event_hash: string;
          retention_class: string;
          retained_until: string | null;
          created_at: string;
          on_hold: boolean;
        }>;
      };
      mcp_key_is_valid: {
        Args: {
          p_key_hash: string;
        };
        Returns: Array<{
          valid: boolean;
          key_id: string;
          tenant_id: string;
          scopes: string[];
        }>;
      };
      mcp_log_usage: {
        Args: {
          p_key_id: string;
          p_action: string;
          p_status: number;
          p_ip?: string | null;
          p_user_agent?: string | null;
          p_latency_ms?: number | null;
          p_error?: string | null;
        };
        Returns: void;
      };
    };
  };
}
