// Supabase Database Types — autogenerated via supabase gen types
// Für Phase 1: simplified. Phase 2: vollständig generiert.

export interface Database {
  public: {
    Tables: {
      evidence_snapshots: {
        Row: {
          id: string;
          tenant_id: string;
          subject_ref: string;
          label: string | null;
          version: number;
          content_sha256: string;
          prev_hash: string | null;
          event_hash: string;
          signature: string | null;
          retention_class: string;
          retained_until: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          subject_ref: string;
          label?: string | null;
          version: number;
          content_sha256: string;
          prev_hash?: string | null;
          event_hash: string;
          signature?: string | null;
          retention_class?: string;
          retained_until?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: never;
      };
      tenants: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          name?: string;
        };
      };
    };
    Views: {};
    Functions: {
      evidence_vault_timeline: {
        Args: {
          p_tenant_id: string;
          p_limit?: number;
        };
        Returns: Array<{
          id: string;
          subject_ref: string;
          label: string | null;
          version: number;
          content_sha256: string;
          event_hash: string;
          retention_class: string;
          retained_until: string | null;
          created_at: string;
          on_hold: boolean;
        }>;
      };
    };
  };
}
