/**
 * Demo-Daten fuer das Runtime-Dashboard.
 *
 * Repraesentieren ein realistisches 24h-Fenster eines Mid-Size-Tenants:
 * 12 Events, drei Vendor-Familien (OpenAI / Anthropic / Microsoft Copilot),
 * Mix aus Routine-Calls (info/low) und kritischen Verstoessen (high/critical).
 *
 * Folge-PRs ersetzen das durch Live-Queries gegen ai_runtime_events.
 */

import type { AiRuntimeEventDemo } from './runtimeTypes';

export const demoRuntimeEvents: AiRuntimeEventDemo[] = [
  {
    id: 'rte-001',
    occurredAt: '2026-05-10T10:14:32Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1',
    user: 'eva.sales@example.com',
    team: 'Sales',
    eventType: 'prompt_sent',
    promptCategory: 'content_generation',
    dataClass: 'personal_data',
    riskLevel: 'high',
    policyStatus: 'warned',
    promptTokens: 1840,
    summary: 'Sales-Mitarbeiter hat Bewerber-Lebenslauf an externes LLM gesendet',
  },
  {
    id: 'rte-002',
    occurredAt: '2026-05-10T10:09:11Z',
    vendor: 'Anthropic',
    model: 'claude-opus-4-7',
    user: 'tom.hr@example.com',
    team: 'HR',
    eventType: 'agent_action',
    promptCategory: 'classification',
    dataClass: 'special_category',
    riskLevel: 'critical',
    policyStatus: 'blocked',
    promptTokens: 920,
    summary: 'HR-Agent versucht Gesundheitsdaten an externes LLM zu senden — geblockt',
  },
  {
    id: 'rte-003',
    occurredAt: '2026-05-10T09:51:02Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1-mini',
    user: 'dev.eng@example.com',
    team: 'Engineering',
    eventType: 'prompt_sent',
    promptCategory: 'code_generation',
    dataClass: 'internal',
    riskLevel: 'low',
    policyStatus: 'allowed',
    promptTokens: 410,
    summary: 'Engineer fragt nach Refactoring-Vorschlag — allowed',
  },
  {
    id: 'rte-004',
    occurredAt: '2026-05-10T09:43:55Z',
    vendor: 'Microsoft',
    model: 'Copilot M365',
    user: 'support.ops@example.com',
    team: 'Support',
    eventType: 'response_received',
    promptCategory: 'summarization',
    dataClass: 'confidential',
    riskLevel: 'medium',
    policyStatus: 'logged',
    summary: 'Copilot fasst internen Ticket-Verlauf zusammen',
  },
  {
    id: 'rte-005',
    occurredAt: '2026-05-10T09:30:18Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1',
    user: 'mark.legal@example.com',
    team: 'Legal',
    eventType: 'file_upload',
    promptCategory: 'extraction',
    dataClass: 'confidential',
    riskLevel: 'high',
    policyStatus: 'requires_approval',
    summary: 'Vertrags-PDF (vermutlich personenbezogen) zur Extraktion hochgeladen',
  },
  {
    id: 'rte-006',
    occurredAt: '2026-05-10T09:18:44Z',
    vendor: 'Anthropic',
    model: 'claude-sonnet-4-6',
    user: 'support.ops@example.com',
    team: 'Support',
    eventType: 'agent_action',
    promptCategory: 'agent_action',
    dataClass: 'internal',
    riskLevel: 'medium',
    policyStatus: 'logged',
    summary: 'Support-Agent triggert Knowledge-Base-Search-Tool',
  },
  {
    id: 'rte-007',
    occurredAt: '2026-05-10T09:02:03Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1',
    user: 'eva.sales@example.com',
    team: 'Sales',
    eventType: 'prompt_sent',
    promptCategory: 'content_generation',
    dataClass: 'public',
    riskLevel: 'info',
    policyStatus: 'allowed',
    summary: 'Marketing-Pitch generiert (oeffentliche Daten)',
  },
  {
    id: 'rte-008',
    occurredAt: '2026-05-10T08:47:21Z',
    vendor: 'Anthropic',
    model: 'claude-opus-4-7',
    user: 'agent-orchestrator@example.com',
    team: 'Engineering',
    eventType: 'tool_call',
    promptCategory: 'agent_action',
    dataClass: 'internal',
    riskLevel: 'low',
    policyStatus: 'logged',
    summary: 'Agent ruft internen Webhook-Tool fuer Deployment-Status auf',
  },
  {
    id: 'rte-009',
    occurredAt: '2026-05-10T08:33:09Z',
    vendor: 'Google',
    model: 'gemini-2.5-pro',
    user: 'mark.legal@example.com',
    team: 'Legal',
    eventType: 'prompt_sent',
    promptCategory: 'qa',
    dataClass: 'public',
    riskLevel: 'info',
    policyStatus: 'allowed',
    summary: 'Legal-Recherche zu DSGVO-Praezedenzfaellen',
  },
  {
    id: 'rte-010',
    occurredAt: '2026-05-10T08:14:55Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1',
    user: 'dev.eng@example.com',
    team: 'Engineering',
    eventType: 'prompt_sent',
    promptCategory: 'code_generation',
    dataClass: 'internal',
    riskLevel: 'low',
    policyStatus: 'allowed',
    summary: 'Pull-Request-Review angefragt',
  },
  {
    id: 'rte-011',
    occurredAt: '2026-05-10T07:58:42Z',
    vendor: 'OpenAI',
    model: 'gpt-4.1',
    user: 'support.ops@example.com',
    team: 'Support',
    eventType: 'prompt_sent',
    promptCategory: 'translation',
    dataClass: 'personal_data',
    riskLevel: 'high',
    policyStatus: 'warned',
    summary: 'Kunden-Email mit personenbezogenen Daten zur Uebersetzung gesendet',
  },
  {
    id: 'rte-012',
    occurredAt: '2026-05-10T07:42:11Z',
    vendor: 'Anthropic',
    model: 'claude-haiku-4-5',
    user: 'mark.legal@example.com',
    team: 'Legal',
    eventType: 'session_end',
    promptCategory: 'analysis',
    dataClass: 'internal',
    riskLevel: 'info',
    policyStatus: 'logged',
    summary: 'Session beendet — 14 Prompts, 0 Verstoesse',
  },
];
