import type { AgentId, EnterpriseAgentDefinition } from './types';

export const enterpriseAgents: EnterpriseAgentDefinition[] = [
  {
    id: 'ai-discovery-agent',
    name: 'AI Discovery Agent',
    shortName: 'Discovery',
    description:
      'Erkennt und inventarisiert KI-Systeme, Modelle, Tools und potenzielle Shadow-AI-Nutzung im Unternehmen.',
    position: {
      layer: 'discovery',
      order: 1,
      upstream: [],
      downstream: ['risk-classification-agent', 'audit-agent'],
      systemBoundary: 'Zwischen Unternehmenssystemen, Connectoren und AI Registry.',
    },
    autonomyLevel: 'observe_only',
    status: 'active',
    capabilities: [
      {
        id: 'detect-ai-systems',
        label: 'KI-Systeme erkennen',
        description: 'Identifiziert KI-Tools, Modelle und AI-SaaS-Nutzung.',
        riskLevel: 'limited',
        requiresHumanApproval: false,
      },
      {
        id: 'shadow-ai-flagging',
        label: 'Shadow AI markieren',
        description: 'Markiert unbekannte oder nicht freigegebene KI-Systeme.',
        riskLevel: 'high',
        requiresHumanApproval: false,
      },
    ],
    inputs: ['connector metadata', 'manual registry entries', 'usage reports'],
    outputs: ['ai_system_registry candidates', 'shadow_ai_findings'],
    allowedActions: ['scan_metadata', 'create_candidate', 'recommend_review'],
    forbiddenActions: ['delete_systems', 'block_users', 'external_notifications'],
    complianceScope: ['DSGVO', 'EU AI Act', 'ISO 27001'],
    auditRequired: true,
    humanApprovalRequired: false,
  },
  {
    id: 'risk-classification-agent',
    name: 'Risk Classification Agent',
    shortName: 'Risk',
    description:
      'Klassifiziert KI-Systeme nach DSGVO-, Daten- und EU-AI-Act-Risiken.',
    position: {
      layer: 'governance',
      order: 2,
      upstream: ['ai-discovery-agent'],
      downstream: ['policy-enforcement-agent', 'audit-agent'],
      systemBoundary: 'Zwischen AI Registry und Policy Engine.',
    },
    autonomyLevel: 'recommend_only',
    status: 'active',
    capabilities: [
      {
        id: 'classify-ai-act-risk',
        label: 'AI-Act-Risiko klassifizieren',
        description: 'Ordnet KI-Systeme in minimal, limited, high oder prohibited ein.',
        riskLevel: 'high',
        requiresHumanApproval: true,
      },
      {
        id: 'classify-data-risk',
        label: 'Datenrisiko bewerten',
        description: 'Bewertet personenbezogene, sensible und geschäftskritische Daten.',
        riskLevel: 'high',
        requiresHumanApproval: true,
      },
    ],
    inputs: ['ai_system_registry', 'usage_context', 'data_categories'],
    outputs: ['risk_classification', 'approval_recommendation'],
    allowedActions: ['classify', 'recommend', 'flag_for_review'],
    forbiddenActions: ['approve_system', 'reject_system', 'modify_policy'],
    complianceScope: ['DSGVO Art. 5', 'DSGVO Art. 6', 'DSGVO Art. 35', 'EU AI Act'],
    auditRequired: true,
    humanApprovalRequired: true,
  },
  {
    id: 'policy-enforcement-agent',
    name: 'Policy Enforcement Agent',
    shortName: 'Policy',
    description:
      'Prüft Agentenaktionen gegen Unternehmensrichtlinien und entscheidet, ob Aktionen erlaubt, blockiert oder freigabepflichtig sind.',
    position: {
      layer: 'policy',
      order: 3,
      upstream: ['risk-classification-agent'],
      downstream: ['audit-agent', 'workflow-agent'],
      systemBoundary: 'Zwischen Agent Runtime und externen Aktionen.',
    },
    autonomyLevel: 'human_approval_required',
    status: 'active',
    capabilities: [
      {
        id: 'evaluate-agent-action',
        label: 'Agentenaktion prüfen',
        description: 'Bewertet Modell, Datenkategorien, Risiko und externe Aktion.',
        riskLevel: 'high',
        requiresHumanApproval: false,
      },
      {
        id: 'block-sensitive-action',
        label: 'Sensitive Aktionen blockieren',
        description: 'Blockiert externe Aktionen mit sensiblen Daten.',
        riskLevel: 'high',
        requiresHumanApproval: false,
      },
    ],
    inputs: ['agent_action', 'agent_policy', 'risk_level', 'data_categories'],
    outputs: ['allowed', 'blocked', 'requires_approval', 'reasons'],
    allowedActions: ['evaluate', 'block', 'require_approval', 'log'],
    forbiddenActions: ['override_human_decision', 'execute_external_action'],
    complianceScope: ['DSGVO', 'EU AI Act', 'Internal Policies'],
    auditRequired: true,
    humanApprovalRequired: false,
  },
  {
    id: 'audit-agent',
    name: 'Audit Agent',
    shortName: 'Audit',
    description:
      'Schreibt revisionsfähige Audit-Events für KI-Systeme, Risiken, Policy-Entscheidungen und Feedback.',
    position: {
      layer: 'audit',
      order: 4,
      upstream: [
        'ai-discovery-agent',
        'risk-classification-agent',
        'policy-enforcement-agent',
        'workflow-agent',
        'remediation-agent',
      ],
      downstream: [],
      systemBoundary: 'Revisionssichere Ereignisschicht.',
    },
    autonomyLevel: 'limited_execution',
    status: 'active',
    capabilities: [
      {
        id: 'write-audit-event',
        label: 'Audit Event schreiben',
        description: 'Protokolliert relevante Governance- und KI-Ereignisse.',
        riskLevel: 'limited',
        requiresHumanApproval: false,
      },
    ],
    inputs: ['agent_event', 'risk_level', 'actor', 'metadata'],
    outputs: ['ai_audit_events'],
    allowedActions: ['write_audit_event', 'attach_metadata'],
    forbiddenActions: ['delete_audit_event', 'modify_audit_history'],
    complianceScope: ['DSGVO Accountability', 'EU AI Act Documentation'],
    auditRequired: false,
    humanApprovalRequired: false,
  },
  {
    id: 'feedback-intelligence-agent',
    name: 'Feedback Intelligence Agent',
    shortName: 'Feedback',
    description:
      'Analysiert Founding-Access-Feedback, clustert Bugs, erkennt Muster und erzeugt Roadmap-Vorschläge.',
    position: {
      layer: 'intelligence',
      order: 5,
      upstream: ['audit-agent'],
      downstream: ['remediation-agent'],
      systemBoundary: 'Zwischen Feedback Reports und Produkt-Roadmap.',
    },
    autonomyLevel: 'recommend_only',
    status: 'experimental',
    capabilities: [
      {
        id: 'cluster-feedback',
        label: 'Feedback clustern',
        description: 'Gruppiert ähnliche Fehler, UX-Probleme und Feature-Wünsche.',
        riskLevel: 'minimal',
        requiresHumanApproval: false,
      },
      {
        id: 'prioritize-feedback',
        label: 'Feedback priorisieren',
        description: 'Bewertet Feedback nach Schweregrad, Häufigkeit und Business Impact.',
        riskLevel: 'limited',
        requiresHumanApproval: true,
      },
    ],
    inputs: ['enterprise_feedback_reports'],
    outputs: ['feedback_clusters', 'roadmap_recommendations'],
    allowedActions: ['cluster', 'summarize', 'recommend_priority'],
    forbiddenActions: ['auto_close_feedback', 'publish_customer_data'],
    complianceScope: ['DSGVO', 'Product Governance'],
    auditRequired: true,
    humanApprovalRequired: true,
  },
  {
    id: 'remediation-agent',
    name: 'Remediation Agent',
    shortName: 'Remediation',
    description:
      'Erzeugt konkrete Handlungsvorschläge zur Behebung von Governance-, DSGVO- und AI-Act-Risiken.',
    position: {
      layer: 'remediation',
      order: 6,
      upstream: ['risk-classification-agent', 'feedback-intelligence-agent'],
      downstream: ['workflow-agent', 'audit-agent'],
      systemBoundary: 'Zwischen Risikobewertung und menschlich freigegebener Umsetzung.',
    },
    autonomyLevel: 'recommend_only',
    status: 'active',
    capabilities: [
      {
        id: 'generate-remediation-plan',
        label: 'Maßnahmenplan erzeugen',
        description: 'Erstellt konkrete Schritte zur Risikoreduktion.',
        riskLevel: 'high',
        requiresHumanApproval: true,
      },
    ],
    inputs: ['risk_findings', 'policy_findings', 'feedback_clusters'],
    outputs: ['remediation_plan', 'implementation_tasks'],
    allowedActions: ['recommend_fix', 'create_task_draft', 'request_approval'],
    forbiddenActions: ['modify_customer_system', 'send_external_email', 'deploy_code'],
    complianceScope: ['DSGVO', 'EU AI Act', 'TOM', 'DSFA'],
    auditRequired: true,
    humanApprovalRequired: true,
  },
  {
    id: 'workflow-agent',
    name: 'Workflow Agent',
    shortName: 'Workflow',
    description:
      'Orchestriert freigegebene Aufgaben zwischen Registry, Policies, Feedback und Audit — ohne unkontrollierte externe Ausführung.',
    position: {
      layer: 'orchestration',
      order: 7,
      upstream: ['policy-enforcement-agent', 'remediation-agent'],
      downstream: ['audit-agent'],
      systemBoundary: 'Zwischen internen Aufgaben und menschlicher Freigabe.',
    },
    autonomyLevel: 'human_approval_required',
    status: 'experimental',
    capabilities: [
      {
        id: 'create-internal-task',
        label: 'Interne Aufgabe erzeugen',
        description: 'Erstellt interne Aufgabenentwürfe für freigegebene Maßnahmen.',
        riskLevel: 'limited',
        requiresHumanApproval: true,
      },
    ],
    inputs: ['approved_recommendations', 'remediation_plan'],
    outputs: ['workflow_task_drafts'],
    allowedActions: ['create_task_draft', 'sequence_steps', 'log_progress'],
    forbiddenActions: ['execute_payment', 'send_contract', 'change_external_system'],
    complianceScope: ['Internal Governance', 'Auditability'],
    auditRequired: true,
    humanApprovalRequired: true,
  },
];

export function getEnterpriseAgent(id: AgentId | string): EnterpriseAgentDefinition | undefined {
  return enterpriseAgents.find((agent) => agent.id === id);
}
