import React from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, Bot, CheckCircle2, Code2, FileBarChart, Globe2, Lock, ScanSearch, ShieldCheck, Sparkles, Vault, Workflow } from 'lucide-react';
import { PublicNav } from '../layout/PublicNav';
import { PublicFooter } from '../layout/PublicFooter';
import { Button } from '../components/Button';
import { Badge } from '../components/Badge';
import { Card } from '../components/Card';

const MODULES = [
  ['Website Compliance Scan', 'Domain prüfen, Findings erkennen und Governance-Report erzeugen.', ScanSearch, '/os/audit'],
  ['Claude Code Optimizer', 'Code analysieren und Datenschutz-/Security-Findings remediieren.', Code2, '/claude-code-optimizer'],
  ['Evidence Vault', 'Kryptografisch verkettete Nachweise und Audit-Trail.', Vault, '/os/evidence'],
  ['Runtime Monitoring', 'Websites, KI-Systeme, Datenflüsse und Risiken kontinuierlich überwachen.', Activity, '/os/app'],
  ['AI-Act Governance', 'KI-Systeme klassifizieren, Controls zuordnen und Lücken schließen.', ShieldCheck, '/os/ai-act'],
  ['Automation', 'Scans, Alerts, Workflows und Remediation verbinden.', Workflow, '/os/automation'],
  ['WhatsApp & Voice AI', 'Auditierbare Chat- und Telefonassistenten.', Bot, '/app/bots'],
  ['Audit Reports', 'Management- und Audit-Berichte aus laufenden Governance-Daten.', FileBarChart, '/os/audit'],
] as const;

const FLOW = [
  ['01', 'DISCOVER', 'Domains, KI-Systeme, Vendoren und Datenflüsse erkennen.'],
  ['02', 'CLASSIFY', 'Risiken und regulatorische Anforderungen einordnen.'],
  ['03', 'ENFORCE', 'Policies und Controls zur Laufzeit durchsetzen.'],
  ['04', 'PROVE', 'Aktionen als nachvollziehbare Evidence sichern.'],
] as const;

export function LandingPageV2() {
  return <div className="min-h-screen overflow-x-hidden bg-[#030810] text-titanium-100">
    <PublicNav />
    <section className="relative isolate overflow-hidden border-b border-white/10">
      <div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_72%_42%,rgba(20,220,255,.18),transparent_25%),radial-gradient(circle_at_90%_8%,rgba(60,100,255,.12),transparent_28%),linear-gradient(115deg,#030810_0%,#07121c_46%,#02060b_100%)]" />
      <div className="mx-auto grid max-w-[1500px] grid-cols-1 items-center gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:py-16">
        <div className="relative z-10">
          <Link to="/claude-code-optimizer" className="inline-flex"><Badge icon={<Sparkles className="h-3 w-3 text-cyan-300" />} className="border-cyan-400/40 bg-cyan-400/5 text-cyan-200">NEU · CLAUDE CODE OPTIMIZER</Badge></Link>
          <h1 className="mt-7 font-display text-5xl font-bold leading-[.94] tracking-[-.04em] text-white sm:text-6xl lg:text-[4.8rem]">Das KI-Betriebssystem<br />für <span className="text-cyan-300">DSGVO, EU AI Act</span><br />&amp; Code-Compliance</h1>
          <p className="mt-6 font-mono text-xs uppercase tracking-[.22em] text-titanium-500">AI GOVERNANCE &amp; CODE OPTIMIZATION OS FOR TRUST &amp; VALUE</p>
          <p className="mt-5 max-w-2xl text-base leading-relaxed text-titanium-300 sm:text-lg">RealSync Dynamics AI überwacht Websites, KI-Systeme, Code und Nachweise kontinuierlich — DSGVO-konform, EU-AI-Act-ready, Claude-Code-geprüft und auditierbar.</p>
          <div className="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-3">{[['DSGVO-KONFORM','Nachweise, Prozesse und Richtlinien automatisiert.'],['AI-ACT-READY','Risikobewertung, Transparenz und Dokumentation.'],['KONTINUIERLICH','Monitoring, Alerts & Evidence in Echtzeit.']].map(([a,b])=><div key={a} className="border-l border-cyan-400/40 pl-3"><div className="font-mono text-[10px] font-bold tracking-[.16em] text-cyan-300">{a}</div><div className="mt-1 text-xs text-titanium-400">{b}</div></div>)}</div>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/os/audit"><Button variant="primary" size="lg">Kostenlosen Audit starten <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link to="/os/app"><Button variant="secondary" size="lg" className="border-white/15 bg-white/[.02]">Plattform live ansehen</Button></Link></div>
        </div>
        <div className="relative min-h-[560px] lg:min-h-[650px]">
          <div className="absolute left-[8%] top-[8%] h-[72%] w-[72%] rounded-full bg-cyan-400/10 blur-3xl" />
          <div className="absolute left-[8%] top-[12%] h-[72%] w-[72%] rounded-full border border-cyan-200/20 bg-[radial-gradient(circle_at_32%_28%,#eefcff_0%,#43d6ff_7%,#126aa0_22%,#071a2b_55%,#02070d_78%)] shadow-[0_0_120px_rgba(32,211,238,.18)]" />
          <div className="absolute left-[18%] top-[28%] h-px w-[55%] rotate-[18deg] bg-cyan-300/70 shadow-[0_0_18px_rgba(34,211,238,.8)]" /><div className="absolute left-[28%] top-[46%] h-px w-[55%] -rotate-[28deg] bg-cyan-300/80 shadow-[0_0_18px_rgba(34,211,238,.8)]" />
          <div className="absolute left-[43%] top-[22%] h-2 w-2 rounded-full bg-cyan-200 shadow-[0_0_18px_8px_rgba(34,211,238,.45)]" /><div className="absolute left-[61%] top-[49%] h-2 w-2 rounded-full bg-cyan-200 shadow-[0_0_18px_8px_rgba(34,211,238,.45)]" />
          <div className="absolute right-[2%] top-[18%] w-44 rounded-xl border border-white/15 bg-[#07111c]/90 p-4 shadow-2xl backdrop-blur-xl"><div className="font-mono text-[10px] text-titanium-500">RISK SCORE</div><div className="mt-1 text-4xl text-white">87<span className="text-sm text-titanium-500"> /100</span></div><div className="mt-3 h-1 rounded-full bg-white/10"><div className="h-1 w-[87%] rounded-full bg-cyan-300" /></div></div>
          <div className="absolute left-[0%] top-[56%] w-48 rounded-xl border border-white/15 bg-[#07111c]/90 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-2 font-mono text-[10px] uppercase text-cyan-300"><Vault className="h-3.5 w-3.5" /> Evidence</div><div className="mt-2 text-2xl text-white">1,248</div><div className="text-xs text-titanium-500">auditfähige Nachweise</div></div>
          <div className="absolute bottom-[9%] right-[2%] w-64 rounded-xl border border-cyan-300/20 bg-[#07111c]/95 p-4 shadow-[0_0_40px_rgba(34,211,238,.12)] backdrop-blur-xl"><div className="font-mono text-[10px] text-cyan-300">CLAUDE CODE AUDIT</div><div className="mt-1 text-3xl text-white">94.2%</div><div className="text-xs text-titanium-400">Code-Ready</div><div className="mt-3 border-t border-white/10 pt-3 text-[10px] text-titanium-500">2.1 Mio. Zeilen · 11,350 Fixes</div></div>
          <div className="absolute bottom-[2%] left-[17%] flex items-center gap-3 rounded-xl border border-white/15 bg-[#07111c]/90 px-4 py-3 backdrop-blur-xl"><Activity className="h-5 w-5 text-cyan-300" /><div><div className="font-mono text-[10px] text-titanium-500">MONITORING</div><div className="text-sm text-white">LIVE</div></div></div>
        </div>
      </div>
      <div className="mx-auto max-w-[1500px] px-5 pb-7 sm:px-8 lg:px-10"><div className="flex flex-wrap gap-x-5 gap-y-2 border-t border-white/10 pt-5 font-mono text-[10px] uppercase tracking-[.15em] text-titanium-500"><span>DSGVO Art. 32</span><span>EU AI Act</span><span>TDDDG</span><span>NIS2</span><span>BAIT</span><span>MaRisk</span><span>EU Hosting</span></div></div>
    </section>

    <section className="border-b border-white/10 bg-[#050c14] py-16"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">FREE GOVERNANCE AUDIT</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Start with a domain. End with evidence.</h2><p className="mt-4 max-w-2xl text-base leading-relaxed text-titanium-400">Domain prüfen, Findings sichtbar machen und daraus die Governance-Roadmap ableiten. Für Websites folgt daraus direkt der Web App Builder — modernes Frontend auf bestehender Backend-Logik.</p></div><Card className="border-cyan-400/20 bg-[#07131e] p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="font-mono text-[10px] text-titanium-500">DOMAIN GOVERNANCE SCAN</div><span className="rounded-full border border-cyan-400/30 px-2 py-1 text-[9px] text-cyan-300">LIVE FLOW</span></div><div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-3"><Globe2 className="h-5 w-5 text-cyan-300" /><span className="font-mono text-sm text-white">your-domain.de</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px]"><div className="rounded-lg border border-white/10 p-3"><div className="text-cyan-300">87</div><div className="text-titanium-600">RISK</div></div><div className="rounded-lg border border-white/10 p-3"><div className="text-white">18</div><div className="text-titanium-600">FINDINGS</div></div><div className="rounded-lg border border-white/10 p-3"><div className="text-white">1,248</div><div className="text-titanium-600">EVIDENCE</div></div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link to="/os/audit"><Button variant="primary" size="md" className="w-full">Audit starten <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link to="/website-builder"><Button variant="secondary" size="md" className="w-full">Website Builder</Button></Link></div></Card></div></section>

    <section className="border-b border-white/10 py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">THE GOVERNANCE LOOP</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Ein Workflow. Eine Runtime. Ein Prüfpfad.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-4">{FLOW.map(([n,t,d])=><div key={n} className="bg-[#07101a] p-6"><div className="font-mono text-[10px] text-cyan-300">{n}</div><h3 className="mt-3 font-display text-lg font-bold text-white">{t}</h3><p className="mt-2 text-sm text-titanium-400">{d}</p></div>)}</div></div></section>

    <section className="border-b border-white/10 bg-[#050c14] py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex items-end justify-between gap-5"><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">ONE OPERATING SYSTEM</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Unsere Elemente — verbunden statt verteilt.</h2></div><Link to="/os/app" className="hidden text-sm font-semibold text-cyan-300 sm:block">Plattform ansehen <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{MODULES.map(([title,text,Icon,to])=><Link key={title} to={to} className="group"><Card className="h-full border-white/10 bg-[#07101a] p-5 transition group-hover:-translate-y-1 group-hover:border-cyan-300/30"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-400/20 bg-cyan-400/5 text-cyan-300"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-sm font-bold text-white">{title}</h3><p className="mt-2 text-xs text-titanium-400">{text}</p></Card></Link>)}</div></div></section>

    <section className="border-b border-white/10 py-16"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">NOT ANOTHER SCANNER</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Vom Snapshot zum laufenden Governance-System.</h2><p className="mt-5 text-base leading-relaxed text-titanium-400">Klassische Scanner liefern einen Zeitpunkt. RealSync verbindet Discovery, Risk Engine, Policy Enforcement, Evidence und Automation zu einer kontinuierlichen Operations-Layer.</p><ul className="mt-7 space-y-3 text-sm text-titanium-300">{['Kontinuierliches Monitoring statt einmaligem Scan','Evidence Vault statt unbeglaubigter Screenshots','EU AI Act Use-Case- und Risikoklassifizierung','Claude Code + Website Builder + Bot-Automation in derselben Plattform'].map(x=><li key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />{x}</li>)}</ul></div><div className="grid gap-4 sm:grid-cols-2"><Card className="border-white/10 bg-[#07101a] p-5"><Lock className="h-5 w-5 text-cyan-300" /><h3 className="mt-4 font-bold text-white">EU-Souveränität</h3><p className="mt-2 text-xs text-titanium-400">EU-Hosting, Datenresidenz und serverseitige Secret-Isolation.</p></Card><Card className="border-cyan-400/20 bg-cyan-400/[.04] p-5"><Vault className="h-5 w-5 text-cyan-300" /><h3 className="mt-4 font-bold text-white">Kryptografische Evidence</h3><p className="mt-2 text-xs text-titanium-400">Hash-Chain, Signatur und Audit-Export für nachvollziehbare Nachweise.</p></Card><Card className="border-white/10 bg-[#07101a] p-5"><ShieldCheck className="h-5 w-5 text-cyan-300" /><h3 className="mt-4 font-bold text-white">Governance Runtime</h3><p className="mt-2 text-xs text-titanium-400">Policies werden zur Laufzeit bewertet, nicht nur dokumentiert.</p></Card><Card className="border-white/10 bg-[#07101a] p-5"><FileBarChart className="h-5 w-5 text-cyan-300" /><h3 className="mt-4 font-bold text-white">Audit-ready</h3><p className="mt-2 text-xs text-titanium-400">Reports und Evidence aus demselben System.</p></Card></div></div></section>

    <section className="relative overflow-hidden py-20 text-center"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_center,rgba(34,211,238,.12),transparent_45%)]" /><p className="font-mono text-[10px] font-bold tracking-[.2em] text-cyan-300">READY TO OPERATE</p><h2 className="mx-auto mt-3 max-w-4xl font-display text-4xl font-bold text-white sm:text-5xl">Bereit zu beweisen, dass Compliance läuft?</h2><p className="mx-auto mt-5 max-w-2xl text-base text-titanium-400">Starten Sie mit einem Free Audit — ohne Account. Discover → Classify → Enforce → Prove auf Ihrer Domain.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><Link to="/os/audit"><Button variant="primary" size="lg">Free Audit starten <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link to="/os/pricing"><Button variant="secondary" size="lg">Preise ansehen</Button></Link></div></section>
    <PublicFooter />
  </div>;
}
