/**
 * SEO-Keyword- und Landing-Page-Ideen fuer die Kampagne
 * "Was Ihre Website wirklich tut".
 *
 * Diese Liste ist eine Inhaltsplanung, KEINE technische Route-Definition.
 * Routen werden in src/App.tsx + src/config/seo.ts gepflegt. Sobald eine
 * Page tatsaechlich gebaut wird, wandert der Eintrag dort hinueber.
 *
 * Konventionen:
 *   - intentTier: top-of-funnel (informational) → bottom (transactional)
 *   - existsAsRoute: true, wenn die Page bereits live ist
 *   - cta: zentral via CTA_TARGETS (kein freier String)
 */

import type { ContentAsset } from '../types';

export interface SEOLandingIdea extends ContentAsset {
  channel: 'seo_landing';
  primaryKeyword: string;
  longTailVariants: string[];
  targetUrl: string;
  intentTier: 'informational' | 'comparative' | 'transactional';
  existsAsRoute: boolean;
  /** Kurze Begruendung, warum die Page strategisch sinnvoll ist. */
  rationale: string;
}

export const SEO_LANDING_IDEAS: SEOLandingIdea[] = [
  {
    id: 'seo-ai-act-website-check',
    channel: 'seo_landing',
    theme: 'ai_act',
    persona: ['compliance_lead', 'kmu_geschaeftsfuehrung'],
    cta: 'free_audit',
    primaryKeyword: 'AI Act Website Check',
    longTailVariants: [
      'EU AI Act Website prüfen',
      'AI Act Compliance Website',
      'KI-Verordnung Website Audit',
    ],
    targetUrl: '/ai-act-website-check',
    intentTier: 'informational',
    existsAsRoute: false,
    rationale: 'AI Act ist 2026 das dominierende Compliance-Thema. Wer „AI Act Website" googelt sucht ein Werkzeug, nicht eine Kanzlei.',
  },
  {
    id: 'seo-cookie-banner-ohne-reject',
    channel: 'seo_landing',
    theme: 'consent_timing',
    persona: ['kmu_geschaeftsfuehrung'],
    cta: 'free_audit',
    primaryKeyword: 'Cookie Banner ohne Reject Button',
    longTailVariants: [
      'Cookie Consent ohne Ablehnen-Button',
      'Cookie-Banner Reject-Button Pflicht',
      'DSGVO Cookie Banner Ablehnen',
    ],
    targetUrl: '/cookie-banner-ohne-reject-button',
    intentTier: 'informational',
    existsAsRoute: false,
    rationale: 'Hohes Suchvolumen aus Selbst-Checks heraus. Zahlt direkt auf unseren USP „technische Realität statt Narrativ" ein.',
  },
  {
    id: 'seo-dsgvo-audit-agenturen',
    channel: 'seo_landing',
    theme: 'partner_program',
    persona: ['agency_owner'],
    cta: 'partners',
    primaryKeyword: 'DSGVO Audit für Agenturen',
    longTailVariants: [
      'DSGVO Tool Agentur',
      'Multi-Tenant DSGVO Dashboard',
      'White Label DSGVO Audit',
    ],
    targetUrl: '/dsgvo-audit-agenturen',
    intentTier: 'comparative',
    existsAsRoute: false,
    rationale: 'Agenturen sind im DACH der schnellste Reseller-Kanal. Eine eigene Landing erlaubt White-Label-Pitch im Fold.',
  },
  {
    id: 'seo-pre-consent-tracking',
    channel: 'seo_landing',
    theme: 'consent_timing',
    persona: ['developer', 'compliance_lead'],
    cta: 'free_audit',
    primaryKeyword: 'Pre-Consent Tracking erkennen',
    longTailVariants: [
      'Tracker vor Consent prüfen',
      'GTM vor Einwilligung',
      'Cookies vor Klick',
    ],
    targetUrl: '/pre-consent-tracking',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existiert bereits in /pages/seo/PreConsentTracking — Content/Copy ggf. an Kampagne anpassen, sonst Status halten.',
  },
  {
    id: 'seo-dsb-software-mandanten',
    channel: 'seo_landing',
    theme: 'partner_program',
    persona: ['dsb_external'],
    cta: 'partners',
    primaryKeyword: 'DSB Software Mehrere Mandanten',
    longTailVariants: [
      'Software für externe Datenschutzbeauftragte',
      'DSB Multi-Mandanten-Tool',
      'Datenschutz-Audit Mandanten Dashboard',
    ],
    targetUrl: '/dsb-software-mandanten',
    intentTier: 'transactional',
    existsAsRoute: false,
    rationale: 'Externe DSBs sind der zweithöchste Hebel. Eigene Landing erlaubt Pricing- und Pilot-Fokus.',
  },
  {
    id: 'seo-ki-system-inventar',
    channel: 'seo_landing',
    theme: 'ai_act',
    persona: ['compliance_lead'],
    cta: 'free_audit',
    primaryKeyword: 'KI-System Inventar Vorlage',
    longTailVariants: [
      'AI Act Inventar Vorlage',
      'Liste KI-Systeme Compliance',
      'KI-Register Unternehmen',
    ],
    targetUrl: '/ki-system-inventar',
    intentTier: 'informational',
    existsAsRoute: false,
    rationale: 'Hohes Top-of-Funnel-Volumen bei „Vorlage". Wir liefern eine echte Vorlage als Magnet + CTA auf Audit.',
  },
  {
    id: 'seo-evidence-runtime',
    channel: 'seo_landing',
    theme: 'evidence_runtime',
    persona: ['developer', 'compliance_lead'],
    cta: 'docs_evidence',
    primaryKeyword: 'Evidence Runtime Compliance',
    longTailVariants: [
      'Compliance Evidence System',
      'Audit Trail Hash Chain',
      'Compliance Beweisführung Technik',
    ],
    targetUrl: '/evidence',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierende /evidence-Page als Hub für Entwickler-getriebene Suchanfragen positionieren.',
  },
  {
    id: 'seo-cookiebot-alternative',
    channel: 'seo_landing',
    theme: 'consent_timing',
    persona: ['kmu_geschaeftsfuehrung'],
    cta: 'pricing',
    primaryKeyword: 'Cookiebot Alternative DACH',
    longTailVariants: [
      'Cookiebot Alternative Deutschland',
      'Cookiebot Konkurrenz EU',
      'Alternative zu Cookiebot ohne USA',
    ],
    targetUrl: '/cookiebot-alternative',
    intentTier: 'comparative',
    existsAsRoute: true,
    rationale: 'Existierende Doorway-Page — Content auf Kampagnen-Positionierung verfeinern.',
  },
  {
    id: 'seo-usercentrics-alternative',
    channel: 'seo_landing',
    theme: 'consent_timing',
    persona: ['kmu_geschaeftsfuehrung'],
    cta: 'pricing',
    primaryKeyword: 'Usercentrics Alternative',
    longTailVariants: [
      'Usercentrics Konkurrenz',
      'Usercentrics Alternative günstiger',
      'CMP Alternative DACH',
    ],
    targetUrl: '/usercentrics-alternative',
    intentTier: 'comparative',
    existsAsRoute: true,
    rationale: 'Existierende Doorway — Kampagnen-Konsistenz prüfen, keine doppelte Page bauen.',
  },
  {
    id: 'seo-ai-act-deadline-2026',
    channel: 'seo_landing',
    theme: 'ai_act',
    persona: ['compliance_lead', 'kmu_geschaeftsfuehrung'],
    cta: 'free_audit',
    primaryKeyword: 'AI Act Deadline 2026',
    longTailVariants: [
      'AI Act Frist 2026',
      'EU AI Act Inkrafttreten',
      'AI Act High Risk Stichtag',
    ],
    targetUrl: '/ai-act-deadline-2026',
    intentTier: 'informational',
    existsAsRoute: false,
    rationale: 'Top-of-Funnel zu konkretem Stichtag. Hohe Saisonalität bis Mitte 2026.',
  },
  {
    id: 'seo-agent-governance',
    channel: 'seo_landing',
    theme: 'agent_governance',
    persona: ['compliance_lead', 'developer'],
    cta: 'free_audit',
    primaryKeyword: 'AI Agent Governance',
    longTailVariants: [
      'Agentic AI Compliance',
      'AI Agent Inventar',
      'Autonome KI-Systeme Governance',
    ],
    targetUrl: '/agent-governance',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierende Page — strategisches Pillar für Agent-Governance-Suchanfragen.',
  },
  {
    id: 'seo-dsfa-vorlage',
    channel: 'seo_landing',
    theme: 'dsgvo_risk',
    persona: ['dsb_internal', 'compliance_lead'],
    cta: 'free_audit',
    primaryKeyword: 'DSFA Vorlage Website',
    longTailVariants: [
      'Datenschutz-Folgenabschätzung Vorlage',
      'DSFA Beispiel Website',
      'DSFA Wizard DSGVO',
    ],
    targetUrl: '/dsfa-wizard',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierender Wizard ist Magnet. SEO-Copy auf Kampagnen-Wording angleichen.',
  },
  {
    id: 'seo-vvt-vorlage',
    channel: 'seo_landing',
    theme: 'dsgvo_risk',
    persona: ['dsb_internal'],
    cta: 'free_audit',
    primaryKeyword: 'VVT Vorlage DSGVO',
    longTailVariants: [
      'Verzeichnis Verarbeitungstätigkeiten Vorlage',
      'VVT Tool DSGVO',
      'VVT Wizard kostenlos',
    ],
    targetUrl: '/vvt-wizard',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierender Wizard. Hohe Conversion in Free-Audit, da hands-on Tool.',
  },
  {
    id: 'seo-evidence-vault',
    channel: 'seo_landing',
    theme: 'evidence_runtime',
    persona: ['compliance_lead', 'kanzlei'],
    cta: 'docs_evidence',
    primaryKeyword: 'Compliance Evidence Vault',
    longTailVariants: [
      'Compliance Beweis Archiv',
      'Audit Hash Chain',
      'Compliance Logs revisionssicher',
    ],
    targetUrl: '/evidence-vault',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierende Pillar-Page. Tech-orientierte Audience.',
  },
  {
    id: 'seo-policy-engine',
    channel: 'seo_landing',
    theme: 'evidence_runtime',
    persona: ['developer', 'compliance_lead'],
    cta: 'docs_evidence',
    primaryKeyword: 'Compliance Policy Engine',
    longTailVariants: [
      'Policy as Code Compliance',
      'OPA Compliance Tool',
      'Regelwerk Engine DSGVO',
    ],
    targetUrl: '/policy-engine',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Bestehende Page — Dev-getriebene Suche anschneiden.',
  },
  {
    id: 'seo-marisk-bait-audit',
    channel: 'seo_landing',
    theme: 'dsgvo_risk',
    persona: ['compliance_lead'],
    cta: 'contact_sales',
    primaryKeyword: 'BAIT MaRisk Website Audit',
    longTailVariants: [
      'MaRisk Anforderungen Website',
      'BAIT Risiko-Analyse Bank',
      'Finanzaufsicht DSGVO Audit',
    ],
    targetUrl: '/bait-marisk-guide',
    intentTier: 'comparative',
    existsAsRoute: true,
    rationale: 'Existierende Page für FinTech / Banken-Audience. Niedrigvolumen, hoher Vertragswert.',
  },
  {
    id: 'seo-schrems-ii-website',
    channel: 'seo_landing',
    theme: 'dsgvo_risk',
    persona: ['compliance_lead', 'dsb_internal'],
    cta: 'free_audit',
    primaryKeyword: 'Schrems II Website prüfen',
    longTailVariants: [
      'US-Drittlandübermittlung Website',
      'DSGVO USA Schrems',
      'Cookie-Tools ohne USA',
    ],
    targetUrl: '/schrems-ii-erklaert',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierende Page — auf Audit-CTA verschärfen.',
  },
  {
    id: 'seo-onetrust-alternative',
    channel: 'seo_landing',
    theme: 'partner_program',
    persona: ['agency_owner', 'compliance_lead'],
    cta: 'pricing',
    primaryKeyword: 'OneTrust Alternative KMU',
    longTailVariants: [
      'OneTrust günstiger',
      'OneTrust Mittelstand Alternative',
      'OneTrust kleine Unternehmen',
    ],
    targetUrl: '/onetrust-alternative',
    intentTier: 'comparative',
    existsAsRoute: true,
    rationale: 'Existierende Doorway. Kampagnen-Konsistenz pruefen.',
  },
  {
    id: 'seo-consent-timing-google-analytics',
    channel: 'seo_landing',
    theme: 'consent_timing',
    persona: ['developer', 'kmu_geschaeftsfuehrung'],
    cta: 'free_audit',
    primaryKeyword: 'Google Analytics Consent DSGVO',
    longTailVariants: [
      'GA4 Consent Mode',
      'Google Analytics ohne Consent',
      'GA Cookie DSGVO',
    ],
    targetUrl: '/google-analytics-consent',
    intentTier: 'informational',
    existsAsRoute: true,
    rationale: 'Existierende Page — sehr hohe Saisonalitaet, ideal fuer Top-of-Funnel.',
  },
  {
    id: 'seo-runtime-governance-vs-cmp',
    channel: 'seo_landing',
    theme: 'evidence_runtime',
    persona: ['compliance_lead'],
    cta: 'pricing',
    primaryKeyword: 'Runtime Governance vs CMP',
    longTailVariants: [
      'Compliance Runtime Tool',
      'Continuous Compliance Plattform',
      'Compliance Monitoring vs Consent Tool',
    ],
    targetUrl: '/runtime-governance-vs-cmp',
    intentTier: 'comparative',
    existsAsRoute: false,
    rationale: 'Eigene Pillar-Page, die den Unterschied zu reinen CMP-Tools klar macht. Niedrigvolumen, hoher Strategic-Fit.',
  },
];
