"""
Parity tests against the TypeScript reference.

The fixtures below were generated by running the canonical_event_bytes
implementation in src/lib/governance/runtime-math.ts of the production
codebase against known-good event envelopes. If a change to canonical.py
breaks these tests, the change is wrong — not the fixtures.
"""
import hashlib

from realsync.canonical import canonical_event_bytes, _to_pg_micro_iso


EV0 = {
    "id": "11111111-1111-1111-1111-111111111111",
    "tenant_id": "22222222-2222-2222-2222-222222222222",
    "global_seq": 1,
    "tenant_seq": 1,
    "spec_version": "1.0",
    "ts": "2026-05-22T10:00:01.000Z",
    "type": "resource.create",
    "severity": "info",
    "source": "gdpr-audit",
    "review_status": "auto",
    "subject_ref": None,
    "payload": {"actor": "admin@acme.corp", "target": "project:alpha"},
    "evidence_refs": [],
    "trace_id": None,
    "correlation_id": None,
    "causation_id": None,
    "prev_hash": None,
}

# Hand-extracted from the TS reference (see project README for procedure).
EV0_CANONICAL_UTF8 = (
    '{"causation_id":null,"correlation_id":null,"evidence_refs":[],'
    '"global_seq":1,"id":"11111111-1111-1111-1111-111111111111",'
    '"payload":{"actor":"admin@acme.corp","target":"project:alpha"},'
    '"prev_hash":null,"review_status":"auto","severity":"info",'
    '"source":"gdpr-audit","spec_version":"1.0","subject_ref":null,'
    '"tenant_id":"22222222-2222-2222-2222-222222222222","tenant_seq":1,'
    '"trace_id":null,"ts":"2026-05-22T10:00:01.000000Z","type":"resource.create"}'
)
EV0_SHA256 = "c58c55d850ec22cad8a8fe84c83a2bd824c4d884e6150794dcccb6d4bfbc5d0b"

EV1 = {
    **EV0,
    "id": "33333333-3333-3333-3333-333333333333",
    "global_seq": 2,
    "tenant_seq": 2,
    "ts": "2026-05-22T10:00:05.000Z",
    "type": "role.assign",
    "payload": {"actor": "admin@acme.corp", "role": "Editor", "target": "user:bob"},
    "prev_hash": EV0_SHA256,
}
EV1_SHA256 = "e807bb9cd7d544149f00219b1672a50e2e84e1be8e7b0bcdaa7dc6d58bfdbc4d"


def test_ev0_canonical_bytes_match_ts_reference():
    actual = canonical_event_bytes(EV0).decode("utf-8")
    assert actual == EV0_CANONICAL_UTF8


def test_ev0_sha256_matches_ts_reference():
    h = hashlib.sha256(canonical_event_bytes(EV0)).hexdigest()
    assert h == EV0_SHA256


def test_ev1_with_prev_hash_string_matches_ts_reference():
    h = hashlib.sha256(canonical_event_bytes(EV1)).hexdigest()
    assert h == EV1_SHA256


def test_ev1_with_prev_hash_bytes_yields_same_canonical():
    # Producer may pass either hex str or raw bytes; output must match.
    ev_bytes = {**EV1, "prev_hash": bytes.fromhex(EV0_SHA256)}
    ev_str   = {**EV1, "prev_hash": EV0_SHA256}
    assert canonical_event_bytes(ev_bytes) == canonical_event_bytes(ev_str)


def test_payload_key_order_does_not_affect_output():
    a = {**EV0, "payload": {"actor": "x", "target": "y"}}
    b = {**EV0, "payload": {"target": "y", "actor": "x"}}
    assert canonical_event_bytes(a) == canonical_event_bytes(b)


def test_missing_required_field_raises():
    import pytest
    bad = {k: v for k, v in EV0.items() if k != "ts"}
    with pytest.raises(KeyError):
        canonical_event_bytes(bad)


def test_ts_normalization_pads_to_microseconds():
    assert _to_pg_micro_iso("2026-05-22T10:00:01Z") == "2026-05-22T10:00:01.000000Z"
    assert _to_pg_micro_iso("2026-05-22T10:00:01.123Z") == "2026-05-22T10:00:01.123000Z"
    # Already-microsecond input gets re-rendered; sub-millisecond precision is dropped.
    assert _to_pg_micro_iso("2026-05-22T10:00:01.123456Z") == "2026-05-22T10:00:01.123000Z"


def test_prev_hash_rejects_non_hex_string():
    import pytest
    bad = {**EV0, "prev_hash": "GHIJKLMNOP" + "0" * 54}
    with pytest.raises(ValueError):
        canonical_event_bytes(bad)


def test_prev_hash_uppercase_normalizes_to_lowercase():
    upper = {**EV1, "prev_hash": EV0_SHA256.upper()}
    lower = {**EV1, "prev_hash": EV0_SHA256}
    assert canonical_event_bytes(upper) == canonical_event_bytes(lower)
