/**
 * Demo data for the Governance Runtime Dashboard.
 *
 * The real dashboard (post-pilot) reads from Supabase via service-role
 * Edge Functions. Until the first browser-extension and SDK emitters
 * exist, the public `/governance-runtime` page renders this fixture so
 * prospects can see the shape of the product.
 *
 * IDs are stable strings (not UUIDs) so cross-references between
 * assets, events, policies, evidence and control-mappings stay
 * readable in the source. They are never persisted.
 */
import type {
  GovernanceAsset,
  GovernanceEvent,
  GovernancePolicy,
  GovernanceEvidence,
  FrameworkControl,
  AssetControlMapping,
} from './types';

const now = (offsetMinutes: number): string =>
  new Date(Date.now() - offsetMinutes * 60_000).toISOString();

export const demoAssets: GovernanceAsset[] = [
  {
    id: 'asset-checkout-bot',
    tenant_id: null,
    asset_type: 'ai_system',
    name: 'Checkout Assistant (Chatbot)',
    description: 'OpenAI-backed shopping assistant on the checkout page.',
    owner_email: 'product@example.de',
    vendor: 'OpenAI',
    system_url: 'https://shop.example.de/checkout',
    data_types: ['customer_message', 'order_history'],
    risk_score: 72,
    ai_act_class: 'limited',
    status: 'active',
    metadata: { region: 'eu-central-1' },
    created_at: now(60 * 24 * 7),
    updated_at: now(45),
  },
  {
    id: 'asset-credit-scorer',
    tenant_id: null,
    asset_type: 'model',
    name: 'Credit-Risk Scorer v3',
    description: 'Internal model predicting payment-default likelihood.',
    owner_email: 'risk@example.de',
    vendor: 'self-hosted',
    system_url: null,
    data_types: ['payment_history', 'address', 'employment'],
    risk_score: 88,
    ai_act_class: 'high',
    status: 'under_review',
    metadata: { team: 'risk-ops' },
    created_at: now(60 * 24 * 30),
    updated_at: now(15),
  },
  {
    id: 'asset-support-summarizer',
    tenant_id: null,
    asset_type: 'agent',
    name: 'Support Ticket Summarizer',
    description: 'Auto-summarizes inbound support tickets for agents.',
    owner_email: 'support-lead@example.de',
    vendor: 'Anthropic',
    system_url: 'https://desk.example.de',
    data_types: ['ticket_body', 'customer_email'],
    risk_score: 34,
    ai_act_class: 'limited',
    status: 'active',
    metadata: {},
    created_at: now(60 * 24 * 14),
    updated_at: now(120),
  },
  {
    id: 'asset-marketing-site',
    tenant_id: null,
    asset_type: 'website',
    name: 'shop.example.de',
    description: 'Public marketing + checkout site.',
    owner_email: 'web@example.de',
    vendor: null,
    system_url: 'https://shop.example.de',
    data_types: ['session_cookie', 'ip_address'],
    risk_score: 41,
    ai_act_class: 'minimal',
    status: 'active',
    metadata: { cms: 'next.js' },
    created_at: now(60 * 24 * 90),
    updated_at: now(8),
  },
];

export const demoPolicies: GovernancePolicy[] = [
  {
    id: 'policy-no-us-transfer',
    tenant_id: null,
    name: 'No personal data to US-only vendors without TIA',
    description: 'Block model calls to vendors without an EU residency option.',
    policy_type: 'data_transfer',
    severity: 'high',
    action: 'block',
    condition: { vendor_region: 'us_only', tia_present: false },
    enabled: true,
    created_at: now(60 * 24 * 30),
    updated_at: now(60 * 24 * 5),
  },
  {
    id: 'policy-high-risk-review',
    tenant_id: null,
    name: 'High-risk AI: human review required',
    description: 'Any AI_ACT high-risk asset needs a sign-off before status=approved.',
    policy_type: 'human_review',
    severity: 'critical',
    action: 'require_approval',
    condition: { ai_act_class: 'high' },
    enabled: true,
    created_at: now(60 * 24 * 30),
    updated_at: now(60 * 24 * 5),
  },
  {
    id: 'policy-log-pii-prompts',
    tenant_id: null,
    name: 'Log prompts that contain PII',
    description: 'Detect names / emails / IBANs in prompts and log to evidence vault.',
    policy_type: 'logging_required',
    severity: 'medium',
    action: 'log',
    condition: { detect: ['email', 'iban', 'name'] },
    enabled: true,
    created_at: now(60 * 24 * 60),
    updated_at: now(60 * 24 * 10),
  },
];

export const demoEvents: GovernanceEvent[] = [
  {
    id: 'event-1',
    tenant_id: null,
    asset_id: 'asset-checkout-bot',
    policy_id: 'policy-log-pii-prompts',
    event_type: 'prompt.pii_detected',
    event_source: 'sdk',
    title: 'Customer email passed into chatbot prompt',
    summary: 'Email address detected in user message — auto-redacted, evidence stored.',
    risk_level: 'medium',
    actor_email: 'customer@example.com',
    vendor: 'OpenAI',
    model_name: 'gpt-4o-mini',
    data_types: ['customer_message', 'email'],
    policy_action: 'log',
    payload: { redacted_fields: ['email'], request_id: 'req_8f2a' },
    created_at: now(7),
  },
  {
    id: 'event-2',
    tenant_id: null,
    asset_id: 'asset-credit-scorer',
    policy_id: 'policy-high-risk-review',
    event_type: 'asset.status_change_requested',
    event_source: 'manual',
    title: 'Credit-Risk Scorer v3 awaiting human sign-off',
    summary: 'High-risk AI asset cannot transition to status=approved without DPO review.',
    risk_level: 'high',
    actor_email: 'risk@example.de',
    vendor: 'self-hosted',
    model_name: 'credit-scorer-v3',
    data_types: ['payment_history', 'address'],
    policy_action: 'require_approval',
    payload: { requested_status: 'approved' },
    created_at: now(45),
  },
  {
    id: 'event-3',
    tenant_id: null,
    asset_id: 'asset-marketing-site',
    policy_id: null,
    event_type: 'scanner.tracker_added',
    event_source: 'website_scanner',
    title: 'New tracker detected: hotjar.com',
    summary: 'Hotjar script appeared on /checkout — not on the approved sub-processor list.',
    risk_level: 'high',
    actor_email: null,
    vendor: 'Hotjar',
    model_name: null,
    data_types: ['session_recording', 'mouse_movement'],
    policy_action: 'warn',
    payload: { url: 'https://shop.example.de/checkout', script: 'https://static.hotjar.com/c/hotjar-...' },
    created_at: now(120),
  },
  {
    id: 'event-4',
    tenant_id: null,
    asset_id: 'asset-checkout-bot',
    policy_id: 'policy-no-us-transfer',
    event_type: 'vendor.region_violation',
    event_source: 'agent_runtime',
    title: 'Blocked: model call to US-only endpoint',
    summary: 'Attempted call to a US-only model endpoint without a Transfer Impact Assessment.',
    risk_level: 'critical',
    actor_email: 'product@example.de',
    vendor: 'OpenAI',
    model_name: 'gpt-4o',
    data_types: ['customer_message'],
    policy_action: 'block',
    payload: { endpoint: 'https://api.openai.com/v1/responses', region: 'us-east-1' },
    created_at: now(240),
  },
  {
    id: 'event-5',
    tenant_id: null,
    asset_id: 'asset-support-summarizer',
    policy_id: null,
    event_type: 'asset.deployed',
    event_source: 'github',
    title: 'Support Summarizer v1.4.2 deployed',
    summary: 'PR #482 merged → new release pushed to production.',
    risk_level: 'info',
    actor_email: 'ci@example.de',
    vendor: 'Anthropic',
    model_name: 'claude-haiku-4-5',
    data_types: [],
    policy_action: 'allow',
    payload: { pr: 482, sha: 'a91c2e' },
    created_at: now(360),
  },
];

export const demoEvidence: GovernanceEvidence[] = [
  {
    id: 'evidence-1',
    tenant_id: null,
    event_id: 'event-1',
    asset_id: 'asset-checkout-bot',
    evidence_type: 'json',
    title: 'Redacted prompt + response (hash-chained)',
    storage_path: 'evidence/2026-05-12/event-1.json.enc',
    content_hash: 'sha256:0c7a…',
    previous_hash: null,
    metadata: { redaction_rule: 'email_v3' },
    created_at: now(7),
  },
  {
    id: 'evidence-2',
    tenant_id: null,
    event_id: 'event-3',
    asset_id: 'asset-marketing-site',
    evidence_type: 'screenshot',
    title: 'Screenshot of /checkout showing Hotjar request',
    storage_path: 'evidence/2026-05-12/event-3.png',
    content_hash: 'sha256:5e21…',
    previous_hash: null,
    metadata: { viewport: '1440x900' },
    created_at: now(120),
  },
  {
    id: 'evidence-3',
    tenant_id: null,
    event_id: 'event-4',
    asset_id: 'asset-checkout-bot',
    evidence_type: 'policy_snapshot',
    title: 'Snapshot of policy "No US transfer" at block-time',
    storage_path: 'evidence/2026-05-12/event-4.policy.json',
    content_hash: 'sha256:9b18…',
    previous_hash: 'sha256:0c7a…',
    metadata: {},
    created_at: now(240),
  },
];

export const demoFrameworkControls: FrameworkControl[] = [
  { id: 'ctl-gdpr-art5',   framework: 'GDPR',      control_code: 'Art.5',  title: 'Principles relating to processing',
    description: 'Lawfulness, fairness, transparency, purpose limitation, data minimisation and accountability.',
    metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-gdpr-art30',  framework: 'GDPR',      control_code: 'Art.30', title: 'Records of processing activities',
    description: 'Maintain records of processing activities.', metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-gdpr-art35',  framework: 'GDPR',      control_code: 'Art.35', title: 'Data protection impact assessment',
    description: 'Assess high-risk processing operations.', metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-aiact-art9',  framework: 'EU_AI_ACT', control_code: 'Art.9',  title: 'Risk management system',
    description: 'Establish and maintain a risk management system for high-risk AI systems.',
    metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-aiact-art12', framework: 'EU_AI_ACT', control_code: 'Art.12', title: 'Record keeping',
    description: 'Enable automatic logging and traceability.', metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-aiact-art14', framework: 'EU_AI_ACT', control_code: 'Art.14', title: 'Human oversight',
    description: 'Ensure appropriate human oversight.', metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-iso-a51',     framework: 'ISO_27001', control_code: 'A.5.1',  title: 'Policies for information security',
    description: 'Define and review policies for information security.', metadata: {}, created_at: now(60 * 24 * 60) },
  { id: 'ctl-soc2-cc72',   framework: 'SOC_2',     control_code: 'CC7.2',  title: 'Monitoring and detection',
    description: 'Monitor system components and detect anomalies.', metadata: {}, created_at: now(60 * 24 * 60) },
];

export const demoControlMappings: AssetControlMapping[] = [
  { id: 'map-1', asset_id: 'asset-credit-scorer',      control_id: 'ctl-aiact-art9',  status: 'in_progress', evidence_id: null, notes: 'Risk management doc drafted, review pending.', updated_at: now(60 * 24 * 3) },
  { id: 'map-2', asset_id: 'asset-credit-scorer',      control_id: 'ctl-aiact-art12', status: 'implemented', evidence_id: 'evidence-3', notes: 'Logging via internal audit trail.', updated_at: now(60 * 24 * 2) },
  { id: 'map-3', asset_id: 'asset-credit-scorer',      control_id: 'ctl-aiact-art14', status: 'gap',         evidence_id: null, notes: 'Human-in-the-loop process not documented.', updated_at: now(60 * 24 * 6) },
  { id: 'map-4', asset_id: 'asset-checkout-bot',       control_id: 'ctl-aiact-art12', status: 'implemented', evidence_id: 'evidence-1', notes: 'All prompts logged via SDK middleware.', updated_at: now(60 * 24 * 1) },
  { id: 'map-5', asset_id: 'asset-checkout-bot',       control_id: 'ctl-gdpr-art30',  status: 'implemented', evidence_id: null, notes: 'Listed in RoPA.', updated_at: now(60 * 24 * 10) },
  { id: 'map-6', asset_id: 'asset-marketing-site',     control_id: 'ctl-gdpr-art5',   status: 'gap',         evidence_id: 'evidence-2', notes: 'Unapproved tracker present.', updated_at: now(60 * 24 * 1) },
  { id: 'map-7', asset_id: 'asset-support-summarizer', control_id: 'ctl-iso-a51',     status: 'implemented', evidence_id: null, notes: 'Security policy applies.', updated_at: now(60 * 24 * 20) },
  { id: 'map-8', asset_id: 'asset-support-summarizer', control_id: 'ctl-soc2-cc72',   status: 'in_progress', evidence_id: null, notes: 'Alerting wiring in progress.', updated_at: now(60 * 24 * 4) },
];
