#!/usr/bin/env node
/**
 * verify-audit-bundle.ts
 *
 * Gate 3: Verify Audit Bundle Offline
 *
 * External auditors use this (no RealSync connection).
 *
 * Usage:
 *   npx ts-node scripts/verify-audit-bundle.ts \
 *     --bundle ./audit-export-abc123.zip
 *
 * Output:
 *   ✓ Manifest signature valid (Ed25519)
 *   ✓ Evidence hash intact
 *   ✓ Chain integrity verified
 *   ✓ Audit authentic and unchanged
 */

import { readFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';
import JSZip from 'jszip';
import crypto from 'crypto';
import { verifyBundleIntegrity, hashJSON, type ExportBundle } from '../src/lib/export-bundle';

interface VerifyArgs {
  bundle: string;
}

function parseArgs(): VerifyArgs {
  const args = process.argv.slice(2);
  const params: Record<string, string> = {};

  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    const value = args[i + 1];
    params[key] = value;
  }

  // Support both .zip file and directory
  const bundleArg = params['bundle'] || '';
  return { bundle: bundleArg };
}

async function verifyBundle(args: VerifyArgs): Promise<void> {
  if (!args.bundle) {
    console.error('❌ Missing required arg: --bundle <path>');
    console.error('\nUsage:');
    console.error('  npx ts-node scripts/verify-audit-bundle.ts --bundle ./audit-export-abc123.zip');
    process.exit(1);
  }

  const bundlePath = resolve(args.bundle);

  console.log(`\n🔐 Verifying Audit Bundle\n`);
  console.log(`   Bundle: ${bundlePath}`);

  // 1. Check file exists
  if (!existsSync(bundlePath)) {
    console.error(`❌ Bundle not found: ${bundlePath}`);
    process.exit(1);
  }

  // 2. Load ZIP
  let zip: JSZip;
  try {
    const zipBuffer = readFileSync(bundlePath);
    zip = await JSZip.loadAsync(zipBuffer);
  } catch (err) {
    console.error(`❌ Failed to read ZIP: ${err instanceof Error ? err.message : 'Unknown error'}`);
    process.exit(1);
  }

  // 3. Extract JSON files
  const errors: string[] = [];

  let manifest: any;
  let evidence: any;
  let decisions: any;
  let chain: any;
  let signature: string;

  try {
    const manifestFile = zip.file('manifest.json');
    if (!manifestFile) throw new Error('manifest.json not found in bundle');
    manifest = JSON.parse(await manifestFile.async('text'));

    const evidenceFile = zip.file('evidence.json');
    if (!evidenceFile) throw new Error('evidence.json not found in bundle');
    evidence = JSON.parse(await evidenceFile.async('text'));

    const decisionsFile = zip.file('decisions.json');
    if (!decisionsFile) throw new Error('decisions.json not found in bundle');
    decisions = JSON.parse(await decisionsFile.async('text'));

    const chainFile = zip.file('chain.json');
    if (!chainFile) throw new Error('chain.json not found in bundle');
    chain = JSON.parse(await chainFile.async('text'));

    const sigFile = zip.file('signature.sig');
    if (!sigFile) throw new Error('signature.sig not found in bundle');
    signature = await sigFile.async('text');
  } catch (err) {
    console.error(`❌ Failed to extract bundle: ${err instanceof Error ? err.message : 'Unknown error'}`);
    process.exit(1);
  }

  console.log(`\n✓ Bundle contents loaded\n`);

  // 4. Verify integrity
  const bundle: ExportBundle & { signature: string } = {
    manifest,
    evidence,
    decisions,
    chain,
    signature,
  };

  const result = verifyBundleIntegrity(bundle);

  // 5. Report findings
  console.log(`📊 Verification Results\n`);

  if (result.valid) {
    console.log(`✅ All checks passed\n`);

    console.log(`🔍 Audit Details`);
    console.log(`   Audit ID:     ${manifest.auditId}`);
    console.log(`   Exported:     ${manifest.exportedAt}`);
    console.log(`   Engine:       ${manifest.engine.version} (${manifest.engine.commit})`);
    console.log(`   Policy Pack:  ${manifest.policyPack.version}`);
    console.log();

    console.log(`📈 Statistics`);
    console.log(`   Findings:     ${evidence.length}`);
    console.log(`   Decisions:    ${decisions.length}`);
    console.log(`   Events:       ${chain.length}`);
    console.log();

    console.log(`🔐 Integrity Verification`);
    console.log(`   ✓ Manifest signature valid (Ed25519)`);
    console.log(`   ✓ Evidence hash intact (SHA256)`);
    console.log(`   ✓ Chain hash intact (SHA256)`);
    console.log(`   ✓ Chain parent links verified`);
    console.log(`   ✓ Version consistency confirmed`);
    console.log();

    console.log(`✨ AUDIT AUTHENTIC & UNCHANGED\n`);
    console.log(`This audit was generated by RealSync ${manifest.engine.version}`);
    console.log(`and has not been tampered with.\n`);
  } else {
    console.error(`❌ Verification failed\n`);

    for (const error of result.errors) {
      console.error(`   ✗ ${error}`);
    }

    console.error();
    console.error(`This audit may be tampered with or corrupted.\n`);

    process.exit(1);
  }

  process.exit(0);
}

verifyBundle(parseArgs()).catch((err) => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
