"""Messung der Build-Artefakte, die das Gate verlangt.

Bis hierher hat der DevOps-Agent die fünf Nachweise hart auf `false` gesetzt.
Das war ehrlich (nichts war gemessen), aber es machte das Gate zu einer
Formalie: Es blockierte immer, und zwar unabhängig vom Build.

Jetzt liegen die generierten Dateien im Workspace, also lässt sich messen.
Vier der fünf Nachweise sind statisch prüfbar, der fünfte nicht:

| Nachweis | Wie gemessen |
|---|---|
| `transparency_notice_enabled` | Marker im generierten Code (Art. 50 EU AI Act) |
| `audit_logging_active` | Aufruf einer Protokollierung im generierten Code |
| `model_card_included` | Datei `MODEL_CARD.md` im Projekt |
| `pii_scan_passed` | keine Treffer der PII-/Secret-Muster |
| `tests_passed` | **nur** durch Ausführen — siehe unten |

**Zu `tests_passed`:** Die Existenz von Testdateien beweist nichts. Der Wert
wird deshalb ausschließlich aus dem Exit-Code eines echten Testlaufs
abgeleitet (`BUILDER_TEST_COMMAND`). Ohne konfiguriertes Kommando bleibt er
`false` — das Gate blockiert dann, und das ist die richtige Antwort: Ein Build
ohne Testnachweis ist kein freigabefähiger Build.

Alle Prüfungen sind Heuristiken auf generiertem Code, keine Zertifizierung.
Der Report nennt deshalb je Nachweis den Grund, damit im Prüfpfad steht,
*warum* etwas als erfüllt galt.

TODO(Scanner): `pii_scan_passed` gegen einen echten Scanner tauschen. Die
Muster unten finden Offensichtliches, keine Namen in Fixtures.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
import signal
from contextlib import suppress
from typing import Dict, List, Tuple

from . import workspace

logger = logging.getLogger("builder.checks")

# Kommando, das im Projektverzeichnis ausgeführt wird. Leer = kein Nachweis.
TEST_COMMAND = os.getenv("BUILDER_TEST_COMMAND", "")
TEST_TIMEOUT_SECONDS = float(os.getenv("BUILDER_TEST_TIMEOUT_SECONDS", "300"))

# Nur Textdateien prüfen — Binaries würden nur Rauschen erzeugen.
TEXT_SUFFIXES = {
    ".ts", ".tsx", ".js", ".jsx", ".py", ".sql", ".md", ".json",
    ".yml", ".yaml", ".toml", ".html", ".css", ".txt", ".env",
}

# Art. 50 EU AI Act: Der Hinweis muss im Interface sichtbar sein. Gesucht wird
# nach der Formulierung, nicht nach einer Konstante — generierter Code hält
# sich an keine Namenskonvention.
TRANSPARENCY_MARKERS = (
    "ki-generiert",
    "ki-hinweis",
    "ai-generated",
    "ai_generated",
    "transparenzhinweis",
    "transparency_notice",
    "generated by ai",
)

AUDIT_MARKERS = (
    "ai_tool_runs",
    "audit_log",
    "auditlog",
    "prüfpfad",
    "pruefpfad",
    "workflow_runs",
)

MODEL_CARD_NAMES = ("model_card.md", "modelcard.md")

# Platzhalter-Domains sind Konvention und kein Befund — sonst schlägt der Scan
# bei jedem generierten Beispiel an und wird ignoriert.
PLACEHOLDER_DOMAINS = ("example.com", "example.org", "example.net", "test.local", "localhost")

PII_PATTERNS: Tuple[Tuple[str, "re.Pattern[str]"], ...] = (
    ("E-Mail-Adresse", re.compile(r"[\w.+-]+@[\w-]+\.[\w.]{2,}")),
    ("IBAN", re.compile(r"\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b")),
    ("Privater Schlüssel", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("API-Schlüssel", re.compile(r"\b(sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16})\b")),
    ("Passwort im Klartext", re.compile(r"(?i)\bpassword\s*[=:]\s*[\"'][^\"'\s]{4,}[\"']")),
)


class BuildReport:
    """Messergebnis eines Builds: Flags plus Begründung je Flag."""

    def __init__(self) -> None:
        self.artifacts: Dict[str, bool] = {}
        self.reasons: Dict[str, str] = {}
        self.findings: List[str] = []

    def set(self, name: str, value: bool, reason: str) -> None:
        self.artifacts[name] = value
        self.reasons[name] = reason

    def as_output(self) -> Dict[str, str]:
        """Flache Form für den Task-Output (nur Strings)."""
        return {
            "check_reasons": "; ".join(f"{k}: {v}" for k, v in sorted(self.reasons.items())),
            "findings": "; ".join(self.findings) if self.findings else "keine",
        }


def _text_files(project_id: str) -> List[Tuple[str, str]]:
    wurzel = workspace.project_root(project_id).resolve()
    dateien = []
    for pfad in workspace.list_files(project_id):
        if pfad.suffix.lower() in TEXT_SUFFIXES:
            dateien.append((str(pfad.relative_to(wurzel)), workspace.read_text(pfad)))
    return dateien


def _enthaelt(dateien: List[Tuple[str, str]], marker: Tuple[str, ...]) -> str:
    """Erster Treffer als 'pfad (marker)' oder leerer String."""
    for pfad, inhalt in dateien:
        klein = inhalt.lower()
        for eintrag in marker:
            if eintrag in klein:
                return f"{pfad} ({eintrag})"
    return ""


def _pii_treffer(dateien: List[Tuple[str, str]]) -> List[str]:
    treffer: List[str] = []
    for pfad, inhalt in dateien:
        for bezeichnung, muster in PII_PATTERNS:
            for fund in muster.findall(inhalt):
                text = fund if isinstance(fund, str) else fund[0]
                if any(domain in text.lower() for domain in PLACEHOLDER_DOMAINS):
                    continue
                treffer.append(f"{bezeichnung} in {pfad}")
                break
    return treffer


def _abbrechen(prozess) -> None:
    """Beendet den Testlauf samt Kindprozessen."""
    try:
        os.killpg(os.getpgid(prozess.pid), signal.SIGKILL)
    except (ProcessLookupError, PermissionError):
        # Schon beendet oder keine eigene Gruppe — dann reicht der Einzelkill.
        with suppress(ProcessLookupError):
            prozess.kill()


async def run_tests(project_id: str) -> Tuple[bool, str]:
    """Führt das konfigurierte Testkommando im Projektverzeichnis aus.

    Der Rückgabewert hängt **nur** am Exit-Code. Ohne konfiguriertes Kommando
    gibt es keinen Nachweis und damit kein `true` — das Gate blockiert dann
    bewusst.
    """
    if not TEST_COMMAND:
        return False, "kein BUILDER_TEST_COMMAND konfiguriert — kein Testnachweis"

    wurzel = workspace.project_root(project_id)
    if not wurzel.exists():
        return False, "kein Workspace vorhanden"

    try:
        prozess = await asyncio.create_subprocess_shell(
            TEST_COMMAND,
            cwd=str(wurzel),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            # Eigene Prozessgruppe, damit der Abbruch unten den ganzen Baum
            # trifft: Ein Testrunner startet Worker, und ein überlebender
            # Worker hält die Pipe offen — dann wartet `wait()` auf ihn und
            # der Timeout wirkt nicht.
            start_new_session=True,
        )
    except OSError as exc:
        return False, f"Testkommando nicht startbar: {exc}"

    try:
        ausgabe, _ = await asyncio.wait_for(prozess.communicate(), timeout=TEST_TIMEOUT_SECONDS)
    except asyncio.TimeoutError:
        _abbrechen(prozess)
        # Auch das Aufräumen bekommt eine Grenze — sonst tauscht man einen
        # hängenden Testlauf gegen ein hängendes Aufräumen.
        with suppress(asyncio.TimeoutError):
            await asyncio.wait_for(prozess.wait(), timeout=5)
        return False, f"Testlauf nach {TEST_TIMEOUT_SECONDS}s abgebrochen"

    if prozess.returncode == 0:
        return True, "Testlauf grün"

    letzte_zeile = (ausgabe or b"").decode("utf-8", "replace").strip().splitlines()
    hinweis = letzte_zeile[-1][:200] if letzte_zeile else ""
    return False, f"Testlauf Exit-Code {prozess.returncode}: {hinweis}"


async def inspect(project_id: str) -> BuildReport:
    """Misst alle fünf Nachweise am Workspace des Projekts."""
    report = BuildReport()
    dateien = _text_files(project_id)

    if not dateien:
        # Ohne generierte Dateien ist nichts erfüllt. Kein Sonderfall, kein
        # Freibrief — ein leerer Build ist kein freigabefähiger Build.
        for name in (
            "transparency_notice_enabled",
            "audit_logging_active",
            "model_card_included",
            "pii_scan_passed",
            "tests_passed",
        ):
            report.set(name, False, "keine generierten Dateien im Workspace")
        report.findings.append("Workspace leer")
        return report

    treffer = _enthaelt(dateien, TRANSPARENCY_MARKERS)
    report.set(
        "transparency_notice_enabled",
        bool(treffer),
        f"Hinweis gefunden in {treffer}" if treffer else "kein Transparenzhinweis im Code",
    )

    treffer = _enthaelt(dateien, AUDIT_MARKERS)
    report.set(
        "audit_logging_active",
        bool(treffer),
        f"Protokollierung gefunden in {treffer}" if treffer else "kein Audit-Logging im Code",
    )

    model_card = next(
        (pfad for pfad, _ in dateien if pfad.lower().rsplit("/", 1)[-1] in MODEL_CARD_NAMES), ""
    )
    report.set(
        "model_card_included",
        bool(model_card),
        f"Model Card: {model_card}" if model_card else "keine MODEL_CARD.md im Projekt",
    )

    pii = _pii_treffer(dateien)
    report.set(
        "pii_scan_passed",
        not pii,
        f"{len(pii)} Treffer" if pii else f"{len(dateien)} Dateien ohne Treffer",
    )
    report.findings.extend(pii)

    bestanden, grund = await run_tests(project_id)
    report.set("tests_passed", bestanden, grund)
    if not bestanden:
        report.findings.append(f"Tests: {grund}")

    return report
