-- Migration: Approval Gates – Deferred RLS Update
-- collision-check: allow-existing-table runtime_approval_gates — Phase 1.2 schema; RLS from Phase 0 remains
-- Phase 1.3: Reserved for future RLS optimization; existing policies remain in place
--
-- Note: Phase 0 (20260516300000_runtime_core.sql) already created RLS policies for
-- runtime_approval_gates using tenant inheritance via runtime_executions subquery.
-- These policies remain sufficient for Phase 1.2 and will be optimized in Phase 1.3+
-- to use the denormalized tenant_id column directly. For now, compatibility is
-- maintained by leaving existing policies unchanged.
--
-- This is a no-op migration. It serves as a placeholder for Phase 1.3 to avoid
-- confusion with the split Phase 1.2/1.3/1.4 structure.
