-- Automatisierungs-Skills: Run-Datenmodell (Phase 2) — SUPERSEDED / NO-OP
--
-- Diese Migration ist ein erneut eingespieltes Duplikat von
-- 20260614100000_automation_skills.sql (kanonisch). Sie legt dieselben vier
-- Tabellen an (automation_skills, automation_runs, automation_run_events,
-- automation_outputs), jedoch mit einem unvereinbaren Schema:
--
--   • automation_skills:  hier `title` — kanonisch ist `name` (20260614100000)
--   • automation_runs.status:  hier DEFAULT 'pending' / CHECK(pending,…)
--                              — kanonisch ist CHECK(queued,…)
--   • automation_outputs:  hier `storage_path`/`metadata`
--                          — kanonisch sind `tenant_id`/`content`/`evidence_hash`
--
-- Maßgeblich ist das Schema aus 20260614100000_automation_skills.sql: die
-- Edge Functions automation-trigger / automation-callback schreiben
-- automation_runs.status = 'queued' und automation_outputs
-- (tenant_id, output_type, content, evidence_hash) — exakt das Juni-14-Schema.
--
-- Da 20260614100000 zuerst läuft, sind die `CREATE TABLE IF NOT EXISTS` hier
-- ohnehin No-ops; das nachfolgende `INSERT … (title …)` brach jedoch mit
-- „column \"title\" does not exist" ab und blockierte die Migrationsprüfung
-- repo-weit. (Identisches Problem wie zuvor in 20260624000004; dort bereits
-- als No-op neutralisiert — diese Datei wurde später unter einem früheren
-- Zeitstempel erneut eingespielt.)
--
-- Bewusst auf einen No-op reduziert (statt gelöscht), um die Migrationshistorie
-- lückenlos zu halten. Schema und Seeds liegen ausschließlich in
-- 20260614100000_automation_skills.sql.
--
-- (Bewusst keine SQL-Anweisungen — diese Migration ist absichtlich leer.)
