-- Entitlement-Katalog auf PLAN_ENTITLEMENTS (shared/pricing.ts) nachziehen.
--
-- ── Befund (Live-DB, 2026-09-20) ──────────────────────────────────────────
--
-- `npm run check:entitlements` ist der Guard fuer genau diesen Drift, laeuft
-- aber in keinem Workflow. Gemessen gegen die Quelle:
--
--   enterprise   3 von 64 Keys vorhanden. Das Produkt zu plan_key
--                'enterprise' traegt nur die drei SiteOS-Keys aus
--                20260912170000 — kein bots.enabled, kein api.access, kein
--                evidence.*, keine Limits. Jeder gateFeature-/requireQuota-
--                Aufruf wirft fuer einen Enterprise-Tenant FORBIDDEN.
--                Vor 20260912170000 hatte das Produkt 0 Keys und wurde vom
--                EXISTS-Guard in tenant_entitlements() uebersprungen; seit
--                der Migration gewinnt es die Aufloesung — mit 3 Keys.
--   starter      bots.chat fehlt
--   growth       bots.chat, bots.appointments, bots.orders fehlen
--   agency       dito
--   partner      dito
--   free_audit   deckungsgleich
--   governance_launch deckungsgleich
--
-- Die drei Bot-Keys existieren nicht einmal im Vokabular (public.entitlements).
-- appointment-book/index.ts prueft `bots.appointments`, order-intake/index.ts
-- prueft `bots.orders`: hasFeature() liefert fuer einen unbekannten Key false
-- — Terminbuchung und Bestellannahme sind damit fuer JEDEN Plan gesperrt,
-- auch fuer die, die sie bezahlen.
--
-- Kein Wert weicht ab, kein Key ist nur in der DB. Die Migration ist deshalb
-- rein additiv fuer den Bestand: bestehende Zeilen behalten ihren Wert
-- (DO UPDATE greift heute in keiner Zeile). Nichts wird geloescht.
--
-- ── Regel ─────────────────────────────────────────────────────────────────
--
-- Quelle ist PLAN_ENTITLEMENTS. Jahresvarianten (`<plan>_yearly`) erhalten
-- denselben Satz wie ihr Monatszwilling — so wie 20260912170000 es tut und
-- wie tenant_entitlements() ueber den `_yearly`-Fallback aufloest.
-- Plaene, die die Quelle nicht kennt (bronze/silver/gold, enterprise_public,
-- free, free_tier), bleiben unberuehrt.
--
-- Der Block unten ist aus shared/pricing.ts erzeugt.
-- test/billing/entitlement-catalog-parity.test.ts haelt ihn an die Quelle
-- gebunden; .github/workflows/entitlement-drift.yml prueft die DB dagegen.

BEGIN;

-- ─── 1. Vokabular: die drei fehlenden Bot-Capability-Keys ────────────────
INSERT INTO public.entitlements (key, description, kind)
SELECT v.key, v.beschreibung, v.kind
FROM (VALUES
  ('bots.chat',         'Bot-Kanal Chat (Website-Widget)',             'boolean'),
  ('bots.appointments', 'Terminbuchung ueber Bots (appointment-book)',  'boolean'),
  ('bots.orders',       'Bestellannahme ueber Bots (order-intake)',     'boolean')
) AS v(key, beschreibung, kind)
WHERE NOT EXISTS (
  SELECT 1 FROM public.entitlements e WHERE e.key = v.key
);

-- ─── 2. Zuordnung Plan → Key → Wert (vollstaendig aus der Quelle) ────────
-- >>> GENERATED FROM shared/pricing.ts PLAN_ENTITLEMENTS >>>
INSERT INTO public.product_entitlements (product_id, entitlement_id, value)
SELECT p.id, e.id, z.value
FROM (VALUES
  ('agency', 'ai.tool.automations', 1),
  ('agency', 'ai.tool.bot_reply', 1),
  ('agency', 'ai.tool.vps_action_advisor', 1),
  ('agency', 'ai.tool.vps_status', 1),
  ('agency', 'ai.tool.workflows', 1),
  ('agency', 'alerts.email', 1),
  ('agency', 'api.access', 1),
  ('agency', 'asset.register', 1),
  ('agency', 'asset.verify', 1),
  ('agency', 'bots.appointments', 1),
  ('agency', 'bots.chat', 1),
  ('agency', 'bots.enabled', 1),
  ('agency', 'bots.human_handoff', 1),
  ('agency', 'bots.multi_channel', 1),
  ('agency', 'bots.orders', 1),
  ('agency', 'bots.voice', 1),
  ('agency', 'bots.whatsapp', 1),
  ('agency', 'bulk.jobs', 1),
  ('agency', 'c2pa.export', 1),
  ('agency', 'compliance.export', 1),
  ('agency', 'dashboard.access', 1),
  ('agency', 'dse.generator', 1),
  ('agency', 'evidence.advanced', 1),
  ('agency', 'evidence.basic_vault', 1),
  ('agency', 'fix.snippets', 1),
  ('agency', 'governance.ai_register', 1),
  ('agency', 'governance.dsgvo_directory', 1),
  ('agency', 'governance.risk_register', 1),
  ('agency', 'limit.ai_calls_monthly', 10000),
  ('agency', 'limit.ai_cost_monthly_cents', 10000),
  ('agency', 'limit.ai_tokens_monthly', 10000000),
  ('agency', 'limit.api_calls_monthly', 25000),
  ('agency', 'limit.automation_runs_monthly', 500),
  ('agency', 'limit.bot_messages_monthly', 10000),
  ('agency', 'limit.bot_voice_minutes_monthly', 500),
  ('agency', 'limit.bots', 10),
  ('agency', 'limit.bulk_jobs_monthly', 50),
  ('agency', 'limit.compliance_exports_monthly', 100),
  ('agency', 'limit.domains', 10),
  ('agency', 'limit.llm_queries_monthly', -1),
  ('agency', 'limit.sites', 10),
  ('agency', 'limit.team_seats', 15),
  ('agency', 'limit.whatsapp_conversations_monthly', 2500),
  ('agency', 'limit.workflow_runs_monthly', 1000),
  ('agency', 'monitoring.daily', 1),
  ('agency', 'monitoring.drift', 1),
  ('agency', 'monitoring.monthly', 1),
  ('agency', 'policy.iso27001', 1),
  ('agency', 'policy.nis2', 1),
  ('agency', 'policy.packs', 1),
  ('agency', 'provenance.advanced', 1),
  ('agency', 'scheduler.enabled', 1),
  ('agency', 'siteos.builder', 1),
  ('agency', 'siteos.publish', 1),
  ('agency', 'sla.priority', 1),
  ('agency', 'team.members', 1),
  ('agency', 'webhooks.enabled', 1),
  ('agency', 'website.scan', 1),
  ('agency', 'website.scan_monthly_limit', -1),
  ('agency', 'whitelabel.reports', 1),
  ('enterprise', 'ai.tool.automations', 1),
  ('enterprise', 'ai.tool.bot_reply', 1),
  ('enterprise', 'ai.tool.vps_action_advisor', 1),
  ('enterprise', 'ai.tool.vps_status', 1),
  ('enterprise', 'ai.tool.workflows', 1),
  ('enterprise', 'alerts.email', 1),
  ('enterprise', 'api.access', 1),
  ('enterprise', 'asset.register', 1),
  ('enterprise', 'asset.verify', 1),
  ('enterprise', 'bots.appointments', 1),
  ('enterprise', 'bots.chat', 1),
  ('enterprise', 'bots.enabled', 1),
  ('enterprise', 'bots.human_handoff', 1),
  ('enterprise', 'bots.multi_channel', 1),
  ('enterprise', 'bots.orders', 1),
  ('enterprise', 'bots.voice', 1),
  ('enterprise', 'bots.whatsapp', 1),
  ('enterprise', 'bulk.jobs', 1),
  ('enterprise', 'c2pa.export', 1),
  ('enterprise', 'compliance.export', 1),
  ('enterprise', 'dashboard.access', 1),
  ('enterprise', 'dse.generator', 1),
  ('enterprise', 'evidence.advanced', 1),
  ('enterprise', 'evidence.basic_vault', 1),
  ('enterprise', 'fix.snippets', 1),
  ('enterprise', 'governance.ai_register', 1),
  ('enterprise', 'governance.dsgvo_directory', 1),
  ('enterprise', 'governance.risk_register', 1),
  ('enterprise', 'limit.agent_runs_monthly', -1),
  ('enterprise', 'limit.ai_calls_monthly', -1),
  ('enterprise', 'limit.ai_cost_monthly_cents', -1),
  ('enterprise', 'limit.ai_tokens_monthly', -1),
  ('enterprise', 'limit.api_calls_monthly', -1),
  ('enterprise', 'limit.automation_runs_monthly', -1),
  ('enterprise', 'limit.bot_messages_monthly', -1),
  ('enterprise', 'limit.bot_voice_minutes_monthly', -1),
  ('enterprise', 'limit.bots', -1),
  ('enterprise', 'limit.bulk_jobs_monthly', -1),
  ('enterprise', 'limit.compliance_exports_monthly', -1),
  ('enterprise', 'limit.domains', -1),
  ('enterprise', 'limit.llm_queries_monthly', -1),
  ('enterprise', 'limit.sites', -1),
  ('enterprise', 'limit.team_seats', -1),
  ('enterprise', 'limit.whatsapp_conversations_monthly', -1),
  ('enterprise', 'limit.workflow_runs_monthly', -1),
  ('enterprise', 'monitoring.daily', 1),
  ('enterprise', 'monitoring.drift', 1),
  ('enterprise', 'monitoring.monthly', 1),
  ('enterprise', 'org.governance', 1),
  ('enterprise', 'policy.iso27001', 1),
  ('enterprise', 'policy.nis2', 1),
  ('enterprise', 'policy.packs', 1),
  ('enterprise', 'provenance.advanced', 1),
  ('enterprise', 'scheduler.enabled', 1),
  ('enterprise', 'siteos.builder', 1),
  ('enterprise', 'siteos.publish', 1),
  ('enterprise', 'sla.priority', 1),
  ('enterprise', 'sso.enabled', 1),
  ('enterprise', 'team.members', 1),
  ('enterprise', 'webhooks.enabled', 1),
  ('enterprise', 'website.scan', 1),
  ('enterprise', 'website.scan_monthly_limit', -1),
  ('enterprise', 'whitelabel.dashboard', 1),
  ('enterprise', 'whitelabel.reports', 1),
  ('free_audit', 'ai_classification.limited', 0),
  ('free_audit', 'bots.count', 0),
  ('free_audit', 'dashboard.access', 1),
  ('free_audit', 'evidence.basic_vault', 1),
  ('free_audit', 'governance.ai_register', 1),
  ('free_audit', 'governance.dsgvo_directory', 1),
  ('free_audit', 'limit.sites', 0),
  ('free_audit', 'reports.export', 0),
  ('free_audit', 'siteos.builder', 0),
  ('free_audit', 'siteos.publish', 0),
  ('free_audit', 'website.scan', 1),
  ('free_audit', 'website.scan_monthly_limit', -1),
  ('governance_launch', 'bots.enabled', 1),
  ('governance_launch', 'compliance.export', 1),
  ('governance_launch', 'dashboard.access', 1),
  ('governance_launch', 'dse.generator', 1),
  ('governance_launch', 'evidence.basic_vault', 1),
  ('governance_launch', 'governance.dsgvo_directory', 1),
  ('governance_launch', 'limit.automation_runs_monthly', 10),
  ('governance_launch', 'limit.bot_messages_monthly', 1000),
  ('governance_launch', 'limit.bots', 1),
  ('governance_launch', 'limit.compliance_exports_monthly', 5),
  ('governance_launch', 'limit.domains', 1),
  ('governance_launch', 'limit.evidence_storage_gb', 5),
  ('governance_launch', 'limit.sites', 1),
  ('governance_launch', 'limit.team_seats', 3),
  ('governance_launch', 'policy.packs', 1),
  ('governance_launch', 'reports.export', 1),
  ('governance_launch', 'siteos.builder', 1),
  ('governance_launch', 'siteos.publish', 0),
  ('governance_launch', 'website.scan', 1),
  ('growth', 'ai.tool.automations', 1),
  ('growth', 'ai.tool.bot_reply', 1),
  ('growth', 'ai.tool.workflows', 1),
  ('growth', 'alerts.email', 1),
  ('growth', 'api.access', 1),
  ('growth', 'asset.register', 1),
  ('growth', 'asset.verify', 1),
  ('growth', 'bots.appointments', 1),
  ('growth', 'bots.chat', 1),
  ('growth', 'bots.enabled', 1),
  ('growth', 'bots.multi_channel', 1),
  ('growth', 'bots.orders', 1),
  ('growth', 'bots.whatsapp', 1),
  ('growth', 'bulk.jobs', 1),
  ('growth', 'c2pa.export', 1),
  ('growth', 'compliance.export', 1),
  ('growth', 'dashboard.access', 1),
  ('growth', 'dse.generator', 1),
  ('growth', 'evidence.advanced', 1),
  ('growth', 'evidence.basic_vault', 1),
  ('growth', 'fix.snippets', 1),
  ('growth', 'governance.ai_register', 1),
  ('growth', 'governance.dsgvo_directory', 1),
  ('growth', 'governance.risk_register', 1),
  ('growth', 'limit.ai_calls_monthly', 2000),
  ('growth', 'limit.ai_cost_monthly_cents', 2000),
  ('growth', 'limit.ai_tokens_monthly', 2000000),
  ('growth', 'limit.api_calls_monthly', 5000),
  ('growth', 'limit.automation_runs_monthly', 100),
  ('growth', 'limit.bot_messages_monthly', 2000),
  ('growth', 'limit.bots', 2),
  ('growth', 'limit.bulk_jobs_monthly', 10),
  ('growth', 'limit.compliance_exports_monthly', 12),
  ('growth', 'limit.domains', 3),
  ('growth', 'limit.llm_queries_monthly', 500),
  ('growth', 'limit.sites', 3),
  ('growth', 'limit.team_seats', 5),
  ('growth', 'limit.whatsapp_conversations_monthly', 500),
  ('growth', 'limit.workflow_runs_monthly', 100),
  ('growth', 'monitoring.daily', 1),
  ('growth', 'monitoring.drift', 1),
  ('growth', 'monitoring.monthly', 1),
  ('growth', 'policy.iso27001', 1),
  ('growth', 'policy.packs', 1),
  ('growth', 'provenance.advanced', 1),
  ('growth', 'scheduler.enabled', 1),
  ('growth', 'siteos.builder', 1),
  ('growth', 'siteos.publish', 1),
  ('growth', 'team.members', 1),
  ('growth', 'webhooks.enabled', 1),
  ('growth', 'website.scan', 1),
  ('growth', 'website.scan_monthly_limit', -1),
  ('partner', 'ai.tool.automations', 1),
  ('partner', 'ai.tool.bot_reply', 1),
  ('partner', 'ai.tool.vps_action_advisor', 1),
  ('partner', 'ai.tool.vps_status', 1),
  ('partner', 'ai.tool.workflows', 1),
  ('partner', 'alerts.email', 1),
  ('partner', 'api.access', 1),
  ('partner', 'asset.register', 1),
  ('partner', 'asset.verify', 1),
  ('partner', 'bots.appointments', 1),
  ('partner', 'bots.chat', 1),
  ('partner', 'bots.enabled', 1),
  ('partner', 'bots.human_handoff', 1),
  ('partner', 'bots.multi_channel', 1),
  ('partner', 'bots.orders', 1),
  ('partner', 'bots.voice', 1),
  ('partner', 'bots.whatsapp', 1),
  ('partner', 'bulk.jobs', 1),
  ('partner', 'c2pa.export', 1),
  ('partner', 'compliance.export', 1),
  ('partner', 'dashboard.access', 1),
  ('partner', 'dse.generator', 1),
  ('partner', 'evidence.advanced', 1),
  ('partner', 'evidence.basic_vault', 1),
  ('partner', 'fix.snippets', 1),
  ('partner', 'governance.ai_register', 1),
  ('partner', 'governance.dsgvo_directory', 1),
  ('partner', 'governance.risk_register', 1),
  ('partner', 'limit.ai_calls_monthly', 50000),
  ('partner', 'limit.ai_cost_monthly_cents', 50000),
  ('partner', 'limit.ai_tokens_monthly', 50000000),
  ('partner', 'limit.api_calls_monthly', 100000),
  ('partner', 'limit.automation_runs_monthly', 2500),
  ('partner', 'limit.bot_messages_monthly', 50000),
  ('partner', 'limit.bot_voice_minutes_monthly', 2500),
  ('partner', 'limit.bots', 50),
  ('partner', 'limit.bulk_jobs_monthly', 500),
  ('partner', 'limit.compliance_exports_monthly', 500),
  ('partner', 'limit.domains', 50),
  ('partner', 'limit.llm_queries_monthly', -1),
  ('partner', 'limit.sites', 50),
  ('partner', 'limit.team_seats', 50),
  ('partner', 'limit.whatsapp_conversations_monthly', -1),
  ('partner', 'limit.workflow_runs_monthly', 2500),
  ('partner', 'monitoring.daily', 1),
  ('partner', 'monitoring.drift', 1),
  ('partner', 'monitoring.monthly', 1),
  ('partner', 'org.governance', 1),
  ('partner', 'policy.iso27001', 1),
  ('partner', 'policy.nis2', 1),
  ('partner', 'policy.packs', 1),
  ('partner', 'provenance.advanced', 1),
  ('partner', 'scheduler.enabled', 1),
  ('partner', 'siteos.builder', 1),
  ('partner', 'siteos.publish', 1),
  ('partner', 'sla.priority', 1),
  ('partner', 'team.members', 1),
  ('partner', 'webhooks.enabled', 1),
  ('partner', 'website.scan', 1),
  ('partner', 'website.scan_monthly_limit', -1),
  ('partner', 'whitelabel.dashboard', 1),
  ('partner', 'whitelabel.reports', 1),
  ('starter', 'ai.tool.automations', 1),
  ('starter', 'alerts.email', 1),
  ('starter', 'asset.verify', 1),
  ('starter', 'bots.chat', 1),
  ('starter', 'bots.enabled', 1),
  ('starter', 'compliance.export', 1),
  ('starter', 'dashboard.access', 1),
  ('starter', 'dse.generator', 1),
  ('starter', 'evidence.basic_vault', 1),
  ('starter', 'governance.ai_register', 1),
  ('starter', 'governance.dsgvo_directory', 1),
  ('starter', 'limit.agent_runs_monthly', 100),
  ('starter', 'limit.automation_runs_monthly', 25),
  ('starter', 'limit.bot_messages_monthly', 500),
  ('starter', 'limit.bots', 1),
  ('starter', 'limit.compliance_exports_monthly', 2),
  ('starter', 'limit.domains', 1),
  ('starter', 'limit.llm_queries_monthly', 100),
  ('starter', 'limit.sites', 1),
  ('starter', 'limit.team_seats', 1),
  ('starter', 'monitoring.monthly', 1),
  ('starter', 'policy.packs', 1),
  ('starter', 'siteos.builder', 1),
  ('starter', 'siteos.publish', 1),
  ('starter', 'website.scan', 1),
  ('starter', 'website.scan_monthly_limit', -1)
) AS z(plan_key, key, value)
JOIN public.entitlements e ON e.key = z.key
JOIN public.products p
  ON p.default_for_plan_key = z.plan_key
  OR p.default_for_plan_key = z.plan_key || '_yearly'
ON CONFLICT (product_id, entitlement_id)
DO UPDATE SET value = EXCLUDED.value
WHERE public.product_entitlements.value IS DISTINCT FROM EXCLUDED.value;
-- <<< GENERATED <<<

COMMIT;
