-- Automatisierungs-Skills: Run-Datenmodell (Phase 2) — SUPERSEDED / NO-OP
--
-- Diese Migration war ein parallel entwickeltes Duplikat von
-- 20260614100000_automation_skills.sql. Beide legten dieselben vier Tabellen an
-- (automation_skills, automation_runs, automation_run_events, automation_outputs),
-- jedoch mit unvereinbaren Schemata:
--
--   • automation_skills:  hier `title` — kanonisch ist `name` (20260614100000)
--   • automation_runs.status:  hier DEFAULT 'pending' / CHECK(pending,…)
--                              — kanonisch ist CHECK(queued,…)
--   • automation_outputs:  hier `storage_path`/`metadata`
--                          — kanonisch sind `tenant_id`/`content`/`evidence_hash`
--
-- Maßgeblich ist das Schema aus 20260614100000_automation_skills.sql: die
-- Edge Functions automation-trigger / automation-callback schreiben
-- automation_runs.status = 'queued' und automation_outputs
-- (tenant_id, output_type, content, evidence_hash) — exakt das Juni-14-Schema.
--
-- Da 20260614100000 zuerst läuft, waren die `CREATE TABLE IF NOT EXISTS` dieser
-- Datei ohnehin No-ops; das nachfolgende `INSERT … (title …)` brach jedoch mit
-- „column \"title\" does not exist" ab und blockierte die Migrationsprüfung.
-- Hätte das Juni-24-Schema gegriffen, wären die Automation-Edge-Functions
-- gebrochen.
--
-- Diese Datei wird daher bewusst auf einen No-op reduziert (statt sie zu löschen,
-- um die Migrationshistorie lückenlos zu halten). Schema und Seeds bleiben
-- ausschließlich in 20260614100000_automation_skills.sql.
--
-- (Bewusst keine SQL-Anweisungen — diese Migration ist absichtlich leer.)
