import type { ControlSignal } from './dsgvoControlPackTypes';

export const DEMO_CONTROL_SIGNALS: ControlSignal[] = [
  {
    id: 'sig-001',
    type: 'new_tracker',
    label: 'Neuer Tracker erkannt',
    domain: 'beispiel.de',
    severity: 'critical',
    detectedAt: '2026-06-09T08:14:00Z',
    summary: 'Meta Pixel (fbq) wurde ohne Consent-Gate auf /checkout geladen. Pre-consent-Request erkannt.',
    evidenceRef: 'sha256:a3f2c1e8b4d07f9a2b5c6e1d8f3a7b2c',
    status: 'open',
  },
  {
    id: 'sig-002',
    type: 'consent_timing',
    label: 'Consent-Timing gebrochen',
    domain: 'beispiel.de',
    severity: 'high',
    detectedAt: '2026-06-09T07:52:00Z',
    summary: 'Google Analytics (gtag.js) wurde 340 ms vor Consent-Banner-Interaktion geladen.',
    evidenceRef: 'sha256:b1e4d9f2a7c3e8b5d0f1a6c2e4b8d3f7',
    status: 'open',
  },
  {
    id: 'sig-003',
    type: 'new_third_party_domain',
    label: 'Neue Third-Party Domain',
    domain: 'beispiel.de',
    severity: 'medium',
    detectedAt: '2026-06-09T06:30:00Z',
    summary: 'Neue Verbindung zu cdn.hotjar.com festgestellt. Nicht in vorheriger Scan-Baseline enthalten.',
    evidenceRef: 'sha256:c7a2f1b4e9d3a6c8b2f5e1d4a7c3b9f2',
    status: 'acknowledged',
  },
  {
    id: 'sig-004',
    type: 'new_cookies',
    label: 'Neue Cookies gesetzt',
    domain: 'beispiel.de',
    severity: 'medium',
    detectedAt: '2026-06-08T22:15:00Z',
    summary: '3 neue Cookies entdeckt: _hjSessionUser_*, _fbp, _gcl_au. Fehlen in Datenschutzerklärung.',
    status: 'open',
  },
  {
    id: 'sig-005',
    type: 'legal_text_changed',
    label: 'Rechtstext geändert',
    domain: 'beispiel.de',
    severity: 'low',
    detectedAt: '2026-06-08T14:00:00Z',
    summary: 'Datenschutzerklärung hat sich geändert (Diff: +47 Zeilen). Letzte Version vom 2026-05-12.',
    evidenceRef: 'sha256:d4b8e2f1c6a3b7d9f2e5a1c4b7e3d8f1',
    status: 'resolved',
  },
  {
    id: 'sig-006',
    type: 'evidence_snapshot',
    label: 'Evidence Snapshot erzeugt',
    domain: 'beispiel.de',
    severity: 'info',
    detectedAt: '2026-06-09T00:00:00Z',
    summary: 'Täglicher Compliance-Snapshot mit 12 Findings versiegelt. HMAC-signiert, unveränderlich.',
    evidenceRef: 'sha256:e9f3a1b2c4d7e8f1a3b5c6d2e4f7a1b3',
    status: 'resolved',
  },
];
