import type { ControlSignal } from './dsgvoControlPackTypes';

export const DEMO_CONTROL_SIGNALS: ControlSignal[] = [
  {
    id: 'sig-001',
    type: 'new_tracker',
    label: 'Neuer Tracker erkannt',
    domain: 'meinshop.de',
    severity: 'critical',
    detectedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    summary: 'Meta Pixel (fbq) wurde ohne vorherige Einwilligung auf /checkout geladen. Drittlandtransfer in die USA ohne SCC-Nachweis.',
    evidenceRef: 'sha256:a3f8c2e1d09b4f7a2c6e3d8b1f4a9c2e5d7b0f3a6c9e2d5b8f1a4c7e0d3b6f9',
    status: 'open',
  },
  {
    id: 'sig-002',
    type: 'consent_timing',
    label: 'Consent-Timing gebrochen',
    domain: 'meinshop.de',
    severity: 'high',
    detectedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    summary: 'Google Analytics (gtag.js) feuerte 340 ms vor Anzeige des Consent-Banners. Art. 7 DSGVO: Einwilligung muss vor Verarbeitung vorliegen.',
    evidenceRef: 'runtime-event:7f3a2c1e-9d4b-4f8a-b2c6-e3d8b1f4a9c2',
    status: 'open',
  },
  {
    id: 'sig-003',
    type: 'new_third_party_domain',
    label: 'Neue Third-Party Domain',
    domain: 'agentur-website.de',
    severity: 'medium',
    detectedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    summary: '3 neue Drittdomains erkannt: cdn.hotjar.com, api.hubspot.com, fonts.typekit.net. Keine DPA für Hotjar vorhanden.',
    evidenceRef: 'storage://evidence/2026-06-06/third-party-scan-agentur.har',
    status: 'acknowledged',
  },
  {
    id: 'sig-004',
    type: 'new_cookies',
    label: 'Neue Cookies erkannt',
    domain: 'meinshop.de',
    severity: 'medium',
    detectedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    summary: '5 neue Cookies gesetzt: _fbp (Marketing, 90 Tage), _ga_XXXXX (Analytics, 2 Jahre), ab_test_variant (Session). Nicht im Cookie-Banner deklariert.',
    evidenceRef: 'sha256:b4e9d3f2c1a8e7b6d5f4c3b2a1e9d8f7c6b5a4e3d2f1c0b9a8e7d6f5c4b3a2e1',
    status: 'open',
  },
  {
    id: 'sig-005',
    type: 'legal_text_changed',
    label: 'Rechtstext geändert',
    domain: 'dienstleister-gmbh.de',
    severity: 'low',
    detectedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    summary: 'Datenschutzerklärung geändert (Diff: +240 Zeichen). Abschnitt "Auftragsverarbeiter" enthält neuen Dienstleister ohne VVT-Eintrag.',
    evidenceRef: 'storage://evidence/2026-06-06/privacy-policy-diff-dienstleister.json',
    status: 'open',
  },
  {
    id: 'sig-006',
    type: 'evidence_snapshot',
    label: 'Evidence Snapshot erzeugt',
    domain: 'meinshop.de',
    severity: 'info',
    detectedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    summary: 'Automatischer Audit-Snapshot für meinshop.de erstellt. 12 Findings dokumentiert, Consent-Layer-Screenshot archiviert, HAR-Datei gespeichert.',
    evidenceRef: 'storage://evidence/2026-06-06/snapshot-meinshop-audit.zip',
    status: 'resolved',
  },
];
